### ISSUE TITLE
Data error (cyclic redundancy check) during "Decrypt"

### ISSUE THREAD

**Issue by FahadMustafa** [AArnott/PCLCrypto#101]
I have a UWP app in the store using v0.0.2 and I am seeing a few instances of this exception:

```
Exception Type:  System.Exception
Crashed Thread:  2

Application Specific Information:
Data error (cyclic redundancy check). (Excep_FromHResult 0x80070017)

Exception Stack:
Csn.UniversalWindows!<BaseAddress>+0x7653bf
Csn.UniversalWindows!<BaseAddress>+0x841ce5
Csn.UniversalWindows!<BaseAddress>+0x8544eb
PCLCrypto.CryptographicEngine.Decrypt(ICryptographicKey key, Byte[] data, Byte[] iv)
SQLite.Net.Cipher.Security.CryptoService.Decrypt(String dataText, String keyText, String ivText)
SQLite.Net.Cipher.Data.SecureDatabase.Decrypt(Object model, String keySeed)
Csn.UniversalWindows!<BaseAddress>+0x8a0d57
Csn.UniversalWindows!<BaseAddress>+0x8a110b
Csn.UniversalWindows.Core.Context.UserContextWrapper.Get()
Csn.UniversalWindows!<BaseAddress>+0x9ba1f7
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

By the looks of it its only happening so far on mobile phones.

In my code I am making a call to `ISecureDatabase.SecureGetAll` when the application starts which is then throwing the exception.

Any ideas ?

**Comment by AArnott** [comment]
Data corruption. Do you sign your data to ensure its integrity?

**Comment by FahadMustafa** [comment]
No, the data isn't signed.

**Comment by AArnott** [comment]
Also, if the key is wrong it can also produce this symptom.
You might try dumping a base64 encoded representation of your private key and ciphertext from the device when the failure occurs using Debug.WriteLine. Then reproduce the failure in your debugger. Copy the base64 output from your debugger's output window and then write some code to run on WinRT or desktop CLR that reads that data and tries to decrypt it. If it succeeds, then we can be reasonably confident it's a genuine problem on that device with decrypting data. But if it fails as well, then there's a problem with the key or the data, and not the device.

**Comment by FahadMustafa** [comment]
The key is being generated using WinRTCrypto and stored in the PasswordVault. I will try and implement the debugging suggestion and see if I can narrow down the cause. It might take a while though, since I could not reproduce the error on any of my machines, just seeing the error through telemetry.

**Comment by AArnott** [comment]
Ok.  I am going to close the issue pending more evidence that it's a bug in the library as opposed to data corruption. 
In general it sounds like a good idea for your app to be tolerant of corruption errors and retry sending the message, reset or whatever makes sense in your scenario.
