### ISSUE TITLE
NetCore support for PCLCrypto.WinRTCrypto.get_MacAlgorithmProvider()

### ISSUE THREAD

**Issue by rutmir** [AArnott/PCLCrypto#102]
Hello, your library is used by AWSSDK developers in the logic of providing access to their services, but it can't be used in NetCore.App environment without implementation PCL block in PCLCrypto.WinRTCrypto. Do you plan to work on this problem?

**Comment by AArnott** [comment]
see also #64. PCLCrypto doesn't support Linux or OSX. It does support iOS, Android, Windows desktop, UWP, WinRT 8.x, and Windows Phone 8-10. 

I think .NET Core projects _might_ be able to use PCLCrypto within the restrictions of the supported operating systems, but I'm not sure.
At present, full .NET Core support on Linux and OSX is not on the roadmap. I'm not against it, but I haven't the capacity right now to add it. We would certainly entertain pull requests that add it, however.

**Comment by rutmir** [comment]
ok, thank you
