### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by AArnott** [AArnott/PCLCrypto#103]
Package up with runtime assemblies in nuget packages at minimum.
Consider supporting OSX, Linux.

**Comment by naster01** [comment]
I currently need it in a project for Windows 10.
It would be cool to support .NETStandard,Version=v1.3.
Thx

**Comment by Trolldemorted** [comment]
support for .NETStandard would be great indeed.

do you have plans for this in the near future?

**Comment by AArnott** [comment]
Yes. Just as soon as dotnet/sdk#650 and dotnet/sdk#651 are fixed, I _think_ I'll be unblocked in utilizing VS2017 to build the netstandard supporting library.

In the meantime, I can probably makeshift it with NuProj. NetStandard support is easier than .NET Core support. @Trolldemorted did you mean to distinguish the two?

**Comment by adminnz** [comment]
Looks like those two dotnet/sdk issues are resolved for you? What is the status of this project supporting .NET core ?

**Comment by AArnott** [comment]
Yes, I suspect I'm unblocked now. Just need to find time.
To be clear, what are you looking for? .NET Core support for running on which OS(s)?

**Comment by adminnz** [comment]
I'm mainly looking at this because its used in [Microsoft's Azure IoT Device Client](https://github.com/Azure/azure-iot-sdk-csharp/tree/master/device) which I'm porting to .NET Core for Linux (specifically Ubuntu)

**Comment by AArnott** [comment]
I see. Thanks. I hope to get to this within the next few weeks. What's your timeframe requirements?

**Comment by adminnz** [comment]
Obviously the sooner the better, but 1-3 weeks is fine.

**Comment by AArnott** [comment]
It's going to be a significant effort. Both to refactor the entire solution to use .NET SDK projects, and then to add support for .netstandard1.6 (or whatever version adds the crypto APIs). So although I think I can start in that timeframe, I don't know how long it will take me. Hopefully not too much longer, but this is a side project for me so "as time permits" is the constraint I'm under.

**Comment by AArnott** [comment]
Work has started in the SDKProj branch.

**Comment by AArnott** [comment]
@adminnz So maybe we got lucky. I spent a few hours last night and this morning to get this going. It's very early, but I have a package that supports .NET Core. It will throw `PlatformNotSupportedException` in quite a few cases, but perhaps it's enough for your scenario? Let me know.

NuGet feed: https://ci.appveyor.com/nuget/pclcrypto
Package version: 2.1.4-g7187deed49

**Comment by AArnott** [comment]
I have a new package version with much better .NET Core support: `2.1.13-alpha+g51fc118017`

Please use the NuGet feed mentioned in my previous comment.

**Comment by francisrath** [comment]
I can't get `2.1.13-alpha+g51fc118017` or the latest test build to work in my Universal Windows app when building with .net native (which is a requirement for the Store). Do you have any updates on this, or maybe someone could help me convert a rather simple decryption method from PCLCrypto to something that would natively work in my Windows 10 app?

Thanks in advance!

**Comment by scharada** [comment]
hi. is there any plan to make the library fully compliant with the latest netstandard20 ? 
thank you

**Comment by AArnott** [comment]
@scharada and others: I've just pushed `2.1.17-alpha-g5b1e8dff8c` to nuget.org with .NET Core and .NETStandard support. Please send your feedback. It's almost completely untested, so no guarantees.

@francisrath You're probably hitting #137 which is a Windows bug that Microsoft is working on. Nothing I can do about it, sadly.
