### ISSUE TITLE
PBKDF2 on iOS

### ISSUE THREAD

**Issue by kspearrin** [AArnott/PCLCrypto#106]
I notice that you do not list iOS as being supported for PBKDF2 key derivation.

iOS has a native implementation for PBKDF2 in CommonCrypto that supports various algorithms:
http://opensource.apple.com//source/CommonCrypto/CommonCrypto-55010/CommonCrypto/CommonKeyDerivation.h

See here for implementation example in `Xamarin.iOS` that PInvokes into CommonCrypto:
https://github.com/bitwarden/mobile/blob/master/src/iOS.Core/Services/CommonCryptoKeyDerivationService.cs

**Comment by AArnott** [comment]
Thank you for the tip.

**Comment by oliverw** [comment]
@AArnott My project uses PCLCrypto and reading this ticket resulted in the method below:

```
private byte[] Pbkdf2(byte[] input, byte[] salt, int iterations, int requestedLength = KeyLength)
{
    try
    {
        var alg = KeyDerivationAlgorithmProvider.OpenAlgorithm(KeyDerivationAlgorithm.Pbkdf2Sha1);
        var parms = KeyDerivationParameters.BuildForPbkdf2(salt, iterations);

        using (var key = alg.CreateKey(input))
        {
            var result = CryptographicEngine.DeriveKeyMaterial(key, parms, requestedLength);
            return result;
        }
    }

    catch (NotSupportedException)
    {
        // Fallback to System.Security.Cryptography
        using (var alg = new System.Security.Cryptography.Rfc2898DeriveBytes(input, salt, iterations))
            return alg.GetBytes(requestedLength);
    }
}

```
Is my fallback to <code>System.Security.Cryptography</code> even necessary or are you doing something like this internally? (couldn't tell from inspecting the source)

**Comment by AArnott** [comment]
The [v2.1.40-alpha release](https://www.nuget.org/packages/PCLCrypto/2.1.40-alpha) on nuget.org includes [some significant changes](https://github.com/AArnott/PCLCrypto/releases/tag/v2.1.40-alpha). I'm optimistic that this issue is either resolved or perhaps does not matter to you any more. Please comment if it still repros and bothers you and we can reactivate.
