### ISSUE TITLE
Failed to run on Mono Linux

### ISSUE THREAD

**Issue by charleypeng** [AArnott/PCLCrypto#107]
I am running an asp server on mono via debian,    the application runs fine on windows but failed on linux.   So i assume that PCLCrypto does not support mono right?  It's hard to find a cross platform crypto lib :0

**Comment by charleypeng** [comment]
I just found that the exception were all about [ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: NCrypt

So i assume that this may be possible to run on mono. Trying to modify it again :)

**Comment by AArnott** [comment]
PCLCrypto runs on mono (as necessary, since it supports Android and iOS, and Xamarin is based on mono). But it doesn't run on Linux. Each OS/platform requires special code.

#103 covers the goal to support OSX and Linux.

**Comment by charleypeng** [comment]
thanks !
