### ISSUE TITLE
CFB

### ISSUE THREAD

**Issue by vbisbest** [AArnott/PCLCrypto#108]
Any chance you will be adding support for AES CFB?  Thanks!

**Comment by AArnott** [comment]
Which platforms are you hoping to use this on?

**Comment by vbisbest** [comment]
All of them :).  I am starting on Android though.

**Comment by AArnott** [comment]
Well, I'm not sure when I'll have time to get to this. But I'd likely accept a PR.

**Comment by AArnott** [comment]
Closing due to a workaround being available or lack of popular demand. This allows us to better focus on high impact issues. If you feel this is blocking you, you may add a comment here to explain why this should be prioritized.

Thank you for your understanding.
