### ISSUE TITLE
Xamarin.Forms - Android problem

### ISSUE THREAD

**Issue by nicolaihenriksen** [AArnott/PCLCrypto#111]
I'm having trouble getting the package to work on Android via a Xamarin.Forms application.

I have installed the package via NuGet in both the portable project as well as both of the platform specific projects. It works perfectly when running the iOS app, however I get the below exception when running the Android app. What am i doing wrong?

I can see the in bin/Debug folder of my Android project that it indeed is the PCLCrypto.dll from the MonoAndroid23 lib within the Nuget package which it copies to the output. Do I need to configure something in the manifest? Something else I am missing?

`PCLCrypto.NotImplementedByReferenceAssemblyException: This is a reference assembly and does not contain implementation. Be sure to install the PCLCrypto package into your application so the platform implementation assembly will be used at runtime.`

/Nicolai

**Comment by AArnott** [comment]
It sounds like you've done everything right. I don't know why the android build would have copied in the wrong assembly.

**Comment by AArnott** [comment]
Closing, as anything more we can do here would be taken care of by #103, as we'd move to the new nupkg layout where reference and implementation assemblies are more explicitly defined.
