### ISSUE TITLE
ComputeHash on large byte arrays

### ISSUE THREAD

**Issue by paulanthonymorris** [AArnott/PCLCrypto#112]
We have a requirement where video files are be sideloaded into an Android app. In order to reliably identify the file and compare it with versions on our server we hash the file on disk. The files can be very large so calling ComputeHash(byte[] bytes) will not scale very well. Would the Transform API work for this? Is there an example of this somewhere?

**Comment by AArnott** [comment]
Yes. The simplest example is the [`AppendTwice` test](https://github.com/AArnott/PCLCrypto/blob/master/src/PCLCrypto.Tests.Shared/HashAlgorithmProviderTests.cs#L88).

But using streams is just about as simple and probably easier to use. You can just do an sync/async Stream.CopyTo[Async] call on a Stream and it will hash it all in the background in a streaming fashion. Check out the [HashByCryptoStream test](https://github.com/AArnott/PCLCrypto/blob/master/src/PCLCrypto.Tests.Shared/HashAlgorithmProviderTests.cs#L99)

**Comment by paulanthonymorris** [comment]
Thanks so much for pointing us in the right direction. Passing in the stream is easy.
