### ISSUE TITLE
Support for .NetStandard 1.x specification

### ISSUE THREAD

**Issue by gameleon-dev** [AArnott/PCLCrypto#116]
Are there any future plans for this library to offer a .Net Standard 1.x (successor to PCL) compatible NuGet package?

Judging by the profile used this library should be compatible with .NET Standard 1.1 and up.

**Comment by AArnott** [comment]
Yes. #103 tracks full on .NET Core support, which is more costly. But mere netstandard support is cheaper, so we'll track it here.

**Comment by AArnott** [comment]
Work for this is going on in the SDKProj branch.

**Comment by fekberg** [comment]
Just curious, any ETA on a first release with support for .NET Standard?

**Comment by AArnott** [comment]
@fekberg Do you need PCLCrypto to work on .NET Core (#103), or is it just .NET Framework you'll run on but want to compile against .netstandard (this issue)?

**Comment by dgeller-OUHSC** [comment]
not fekberg but our team is only worried about the netstandard compilation.

**Comment by fekberg** [comment]
@AArnott Use it with .NET Standard 2.0.

**Comment by stannynuytkens** [comment]
I really need this for .NET Standard 1.2 _(legacy support for win81 and wp8)_

**Comment by AArnott** [comment]
This is in the 2.1 version on nuget.org

**Comment by dgeller-OUHSC** [comment]
I haven't seen this pop up yet on nuget @AArnott, is there a hangup?

**Comment by AArnott** [comment]
@dgeller-OUHSC I'm not sure why you're not seeing it. [It's there](https://www.nuget.org/packages/PCLCrypto/2.1.17-alpha-g5b1e8dff8c):

![image](https://user-images.githubusercontent.com/3548/38822716-2233ce84-4159-11e8-8223-80efc3d1f792.png)

**Comment by dgeller-OUHSC** [comment]
Ah I was waiting around in stable channel-my mistake. thanks!

**Comment by AArnott** [comment]
Once we have a few reports that it works (or I have more time to test it myself), I'll prepare a stable release for it.
