### ISSUE TITLE
Decrypt takes a very long time.

### ISSUE THREAD

**Issue by sstilsonredarrow** [AArnott/PCLCrypto#119]
Decryption on Xamarin.Android is very slow.  I am using AsymmetricAlgorythm .RsaPkcs1 and the Sha1 hash algorythm .  I have a screen shot which illustrates the problem.  The encryption is responsive, taking only a few milliseconds to encrypt 2K of data but, as illustrated in the Xamarin profiler, the decryption of the same data is taking > 1 second.  It may very well be something I am doing wrong but wanted to bring it to your attention.

![profiler](https://cloud.githubusercontent.com/assets/21957295/22804306/1363bd20-eede-11e6-8311-3c85ac5caf13.PNG)

**Comment by AArnott** [comment]
How many bytes are you decrypting?

**Comment by sstilsonredarrow** [comment]
I use a 128 byte key and encrypt in chunks of that size.  Right now the payloads we are encrypting/decrypting are JSON objects of approx. 2K in size but will likely grow to over 12-14K.

**Comment by sstilsonredarrow** [comment]
Andrew, if it helps, here is my code which performs the decryption:
 public string Decrypt(string stringToDecrypt)
        {           
            string decryptedString = string.Empty;
            int bytesRead = 0;
            int decryptSize = inputBlockSize; //Need this to get to a size that is a multiple of 4.
            byte[] bytes = GetCryptoKey();  // Gets the key from the keystore.
            if ( bytes == null)  //This should never happen -- the key should be in the keystore or else they can't decrypt stuff.
            {
                return string.Empty;
            }
            RecreateKey(bytes);  //This recreates the key from the byte blob format, calling the import key.
            byte[] littleBuf = new byte[decryptSize];

            for ( bytesRead = 0; bytesRead < stringToDecrypt.Length; bytesRead += conversionSize)
            {
                string subber = stringToDecrypt.Substring(bytesRead, conversionSize);
                var encrypted = Convert.FromBase64String(subber);
                try
                {
                    var decrypted = CryptographicEngine.Decrypt(Key, encrypted);
                    var decryptedSmall = Encoding.UTF8.GetString(decrypted, 0, decrypted.Length);
                    decryptedString += decryptedSmall;
                }
                catch (System.Exception ex)
                {
                    Debug.WriteLine(ex.Message);
                }
            }                       
            return decryptedString;
        }

**Comment by AArnott** [comment]
I suspect when you say 1028 byte key you actually mean 1028 *bits*. 

Don't use your asymmetric key to encrypt/decrypt data. It's far too slow for that. That's not a PCLCrypto issue, that's just asymmetric cryptography for you. It's only meant to encrypt/decrypt very small amounts of data (about the size of a symmetric key). So when you need to encrypt data, come up with a cryptographically random symmetric key and use that to encrypt your data. Then encrypt your symmetric key using your asymmetric key.
Then for decryption of course reverse the process.
