### ISSUE TITLE
ILMerge and internalize the Validation dependency

### ISSUE THREAD

**Issue by damianh** [AArnott/PCLCrypto#12]
Hi nice lib!

The Validation reference is non-transitive, i.e. a purely internal concern. It should be ilmerged `/internalize` and thus not be added as a reference to projects consuming PCLCrypto.

Cheers.

**Comment by AArnott** [comment]
Ilmerge is an unsupported tool and in my experience can cause issues. We'll take advantage of any solution nuget offers when available.
