### ISSUE TITLE
 AES encryption/decryption failed in UWP app

### ISSUE THREAD

**Issue by pzs7602** [AArnott/PCLCrypto#120]
in my uwp app, I use the sample code from C# recipes:
            byte[] keyMaterial = Encoding.UTF8.GetBytes("mypassword");
            byte[] data = Encoding.UTF8.GetBytes("Hello,world");
            var provider = WinRTCrypto.SymmetricKeyAlgorithmProvider.OpenAlgorithm(SymmetricAlgorithm.AesCbcPkcs7);
            var key = provider.CreateSymmetricKey(keyMaterial);

            // The IV may be null, but supplying a random IV increases security.
            // The IV is not a secret like the key is.
            // You can transmit the IV (w/o encryption) alongside the ciphertext.
            var iv = WinRTCrypto.CryptographicBuffer.GenerateRandom(provider.BlockLength);

            byte[] cipherText = WinRTCrypto.CryptographicEngine.Encrypt(key, data);  // error occurs here

            // When decrypting, use the same IV that was passed to encrypt.
            byte[] plainText = WinRTCrypto.CryptographicEngine.Decrypt(key, cipherText);
 
when running, the error occurs:
System.ArgumentException:  NT_STATUS error: STATUS_INVALID_PARAMETER (0xC000000D)
what's wrong?
I use PCLCrypto nuget package 2.0.145

**Comment by AArnott** [comment]
Well, I notice that although you generate an IV, you're not supplying one.

**Comment by pzs7602** [comment]
The document says the IV parameter may be null, and the default parameter value of   method WinRTCrypto.CryptographicEngine.Encrypt's third parameter is null.
The error is the same even I add the IV parameter:
        var iv = WinRTCrypto.CryptographicBuffer.GenerateRandom(provider.BlockLength);
        byte[] cipherText = WinRTCrypto.CryptographicEngine.Encrypt(key, data,iv);

**Comment by AArnott** [comment]
Well, it was a shot. How do you create your `key`?
Generally speaking, as PCLCrypto is just a pass-through to native OS crypto, the next thing you might do is try reading up on the docs for the native method.

**Comment by pzs7602** [comment]
key was created:
byte[] keyMaterial = Encoding.UTF8.GetBytes("mypassword");
 byte[] data = Encoding.UTF8.GetBytes("Hello,world");
 var provider = WinRTCrypto.SymmetricKeyAlgorithmProvider.OpenAlgorithm(SymmetricAlgorithm.AesCbcPkcs7);
 var key = provider.CreateSymmetricKey(keyMaterial);
// encrypt text
var iv = WinRTCrypto.CryptographicBuffer.GenerateRandom(provider.BlockLength);
 byte[] cipherText = WinRTCrypto.CryptographicEngine.Encrypt(key, data,iv);

**Comment by AArnott** [comment]
Ah, you key is the wrong length, almost certainly. 
Please see [this recipe](https://github.com/AArnott/PCLCrypto/wiki/Crypto-Recipes#derive-a-symmetric-key-from-a-password) to turn a password into a key. Your key length must be a certain number of bits long based on the security you need. (256 bits for AES is common).

**Comment by pzs7602** [comment]
Thanks! the code below works:

            byte[] data = Encoding.UTF8.GetBytes("hello,world");
            var provider = WinRTCrypto.SymmetricKeyAlgorithmProvider.OpenAlgorithm(SymmetricAlgorithm.AesCbcPkcs7);

            byte[] salt = Encoding.UTF8.GetBytes(""); // empty string for simplicity. best initialized to a unique value for each user, and stored with the user record
            int iterations = 5000; // higher makes brute force attacks more expensive
            int keyLengthInBytes = 32;  // 256 bits length. key length must be a certain number of bits long based on the security you need. (256 bits for AES is common).
            byte[] keyMaterial = NetFxCrypto.DeriveBytes.GetBytes("mypassword", salt, iterations, keyLengthInBytes);
            var key = provider.CreateSymmetricKey(keyMaterial);
            // The IV may be null, but supplying a random IV increases security.
            // The IV is not a secret like the key is.
            // You can transmit the IV (w/o encryption) alongside the ciphertext.
            var iv = WinRTCrypto.CryptographicBuffer.GenerateRandom(provider.BlockLength);

            byte[] cipherText = WinRTCrypto.CryptographicEngine.Encrypt(key, data);
            // When decrypting, use the same IV that was passed to encrypt.
            byte[] plainTextBytes = WinRTCrypto.CryptographicEngine.Decrypt(key, cipherText);
            string plainText = Encoding.UTF8.GetString(plainTextBytes, 0, plainTextBytes.Length);

**Comment by AArnott** [comment]
great!
