### ISSUE TITLE
PBKDF2_SHA1 key derivation on xamarin apps

### ISSUE THREAD

**Issue by cansado2930** [AArnott/PCLCrypto#121]
Hello
I have found this plugin for xamarin and it is very usefull. So I would like to integrate it on my projects. I have an app for windows phone 8.1, windows 8.1 and windows 10 uwp that are using the following code.

```csharp
public static byte[] Encrypt(string plainText, string pw, string salt)
{
	IBuffer pwBuffer = CryptographicBuffer.ConvertStringToBinary(pw, BinaryStringEncoding.Utf8);
	IBuffer saltBuffer = CryptographicBuffer.ConvertStringToBinary(salt, BinaryStringEncoding.Utf16LE);
	IBuffer plainBuffer = CryptographicBuffer.ConvertStringToBinary(plainText, BinaryStringEncoding.Utf16LE);
	// Derive key material for password size 32 bytes for AES256 algorithm
	KeyDerivationAlgorithmProvider keyDerivationProvider = Windows.Security.Cryptography.Core.KeyDerivationAlgorithmProvider.OpenAlgorithm("PBKDF2_SHA1");
	// using salt and 1000 iterations
	KeyDerivationParameters pbkdf2Parms = KeyDerivationParameters.BuildForPbkdf2(saltBuffer, 1000);
	// create a key based on original key and derivation parmaters
	CryptographicKey keyOriginal = keyDerivationProvider.CreateKey(pwBuffer);
	IBuffer keyMaterial = CryptographicEngine.DeriveKeyMaterial(keyOriginal, pbkdf2Parms, 32);
	CryptographicKey derivedPwKey = keyDerivationProvider.CreateKey(pwBuffer);
	// derive buffer to be used for encryption salt from derived password key 
	IBuffer saltMaterial = CryptographicEngine.DeriveKeyMaterial(derivedPwKey, pbkdf2Parms, 16);
	// display the buffers – because KeyDerivationProvider always gets cleared after each use, they are very similar unforunately
	string keyMaterialString = CryptographicBuffer.EncodeToBase64String(keyMaterial);
	string saltMaterialString = CryptographicBuffer.EncodeToBase64String(saltMaterial);
	SymmetricKeyAlgorithmProvider symProvider = SymmetricKeyAlgorithmProvider.OpenAlgorithm("AES_CBC_PKCS7");
	// create symmetric key from derived password key
	CryptographicKey symmKey = symProvider.CreateSymmetricKey(keyMaterial);
	// encrypt data buffer using symmetric key and derived salt material
	IBuffer resultBuffer = CryptographicEngine.Encrypt(symmKey, plainBuffer, saltMaterial);
	byte[] result;
	CryptographicBuffer.CopyToByteArray(resultBuffer, out result);
	return result;
}
public static string Decrypt(byte[] encryptedData, string pw, string salt)
{
	IBuffer pwBuffer = CryptographicBuffer.ConvertStringToBinary(pw, BinaryStringEncoding.Utf8);
	IBuffer saltBuffer = CryptographicBuffer.ConvertStringToBinary(salt, BinaryStringEncoding.Utf16LE);
	IBuffer cipherBuffer = CryptographicBuffer.CreateFromByteArray(encryptedData);
	// Derive key material for password size 32 bytes for AES256 algorithm
	KeyDerivationAlgorithmProvider keyDerivationProvider = Windows.Security.Cryptography.Core.KeyDerivationAlgorithmProvider.OpenAlgorithm("PBKDF2_SHA1");
	// using salt and 1000 iterations
	KeyDerivationParameters pbkdf2Parms = KeyDerivationParameters.BuildForPbkdf2(saltBuffer, 1000);
	// create a key based on original key and derivation parmaters
	CryptographicKey keyOriginal = keyDerivationProvider.CreateKey(pwBuffer);
	IBuffer keyMaterial = CryptographicEngine.DeriveKeyMaterial(keyOriginal, pbkdf2Parms, 32);
	CryptographicKey derivedPwKey = keyDerivationProvider.CreateKey(pwBuffer);
	// derive buffer to be used for encryption salt from derived password key 
	IBuffer saltMaterial = CryptographicEngine.DeriveKeyMaterial(derivedPwKey, pbkdf2Parms, 16);
	// display the keys – because KeyDerivationProvider always gets cleared after each use, they are very similar unforunately
	string keyMaterialString = CryptographicBuffer.EncodeToBase64String(keyMaterial);
	string saltMaterialString = CryptographicBuffer.EncodeToBase64String(saltMaterial);
	SymmetricKeyAlgorithmProvider symProvider = SymmetricKeyAlgorithmProvider.OpenAlgorithm("AES_CBC_PKCS7");
	// create symmetric key from derived password material
	CryptographicKey symmKey = symProvider.CreateSymmetricKey(keyMaterial);
	// encrypt data buffer using symmetric key and derived salt material
	IBuffer resultBuffer = CryptographicEngine.Decrypt(symmKey, cipherBuffer, saltMaterial);
	string result = CryptographicBuffer.ConvertBinaryToString(BinaryStringEncoding.Utf16LE, resultBuffer);
	return result;
}
```

And I would like to use it in order to integrate the encryption for xamarin forms on android and ios. I have readed on documentation that the algorithm that I'm using isn`t available on android and ios. Is it correct?
Are there some solutions before of change all encryption on published apps?
Thanks you

**Comment by AArnott** [comment]
I don't recall for sure whether the doc is current on this point. I suggest you try a quick Android and iOS app with this key derivation algorithm to see if it works.

**Comment by cansado2930** [comment]
Thanks for your fast answer. I have installed it on a new Xamarin forms app and PBKDF2_SHA1 isn't available. Then, I have to implement it manually if Android and iOS support it.
Best regards

**Comment by AArnott** [comment]
Feel free to send a PR to add support for it to this library. I don't remember why I didn't support it -- probably just lack of time.

**Comment by cansado2930** [comment]
Hello,
I have to ask you sorry, because it seems that I understood the code bad, and I didn't see as I should do.  And it works perfectly between devices with xamarin apps. But I have a problem that I think that it relationated with utf16_le but I don't sure it.
This is the new code in order to encrypt/decrypt with your plugin.

`public static byte[] Encrypt(string plainText, string pw, string salt)
        {
            byte[] pwBuffer = WinRTCrypto.CryptographicBuffer.ConvertStringToBinary(pw, System.Text.Encoding.UTF8);
            byte[] saltBuffer = WinRTCrypto.CryptographicBuffer.ConvertStringToBinary(salt, System.Text.Encoding.UTF8);
            byte[] plainBuffer = WinRTCrypto.CryptographicBuffer.ConvertStringToBinary(plainText, System.Text.Encoding.UTF8);
            IKeyDerivationAlgorithmProvider keyDerivationProvider = WinRTCrypto.KeyDerivationAlgorithmProvider.OpenAlgorithm(KeyDerivationAlgorithm.Pbkdf2Sha1);
            IKeyDerivationParameters pbkdf2Parms = WinRTCrypto.KeyDerivationParameters.BuildForPbkdf2(saltBuffer, 1000);
            ICryptographicKey keyOriginal = keyDerivationProvider.CreateKey(pwBuffer);
            byte[] keyMaterial = WinRTCrypto.CryptographicEngine.DeriveKeyMaterial(keyOriginal, pbkdf2Parms, 32);
            ICryptographicKey derivedPwKey = keyDerivationProvider.CreateKey(pwBuffer);
            byte[] saltMaterial = WinRTCrypto.CryptographicEngine.DeriveKeyMaterial(derivedPwKey, pbkdf2Parms, 16);
            string keyMaterialString = WinRTCrypto.CryptographicBuffer.EncodeToBase64String(keyMaterial);
            string saltMaterialString = WinRTCrypto.CryptographicBuffer.EncodeToBase64String(saltMaterial);
            ISymmetricKeyAlgorithmProvider symProvider = WinRTCrypto.SymmetricKeyAlgorithmProvider.OpenAlgorithm(SymmetricAlgorithm.AesCbcPkcs7);
            ICryptographicKey key = symProvider.CreateSymmetricKey(keyMaterial);
            ICryptographicKey symmKey = symProvider.CreateSymmetricKey(keyMaterial);
            byte[] resultBuffer = WinRTCrypto.CryptographicEngine.Encrypt(symmKey, plainBuffer, saltMaterial);
            byte[] result;
            WinRTCrypto.CryptographicBuffer.CopyToByteArray(resultBuffer, out result);
            return result;
        }
        public static string Decrypt(byte[] encryptedData, string pw, string salt)
        {
            byte[] pwBuffer = WinRTCrypto.CryptographicBuffer.ConvertStringToBinary(pw, System.Text.Encoding.UTF8);
            byte[] saltBuffer = WinRTCrypto.CryptographicBuffer.ConvertStringToBinary(salt, System.Text.Encoding.UTF8);
            byte[] cipherBuffer = WinRTCrypto.CryptographicBuffer.CreateFromByteArray(encryptedData);
            IKeyDerivationAlgorithmProvider keyDerivationProvider = WinRTCrypto.KeyDerivationAlgorithmProvider.OpenAlgorithm(KeyDerivationAlgorithm.Pbkdf2Sha1);
            IKeyDerivationParameters pbkdf2Parms = WinRTCrypto.KeyDerivationParameters.BuildForPbkdf2(saltBuffer, 1000);
            ICryptographicKey keyOriginal = keyDerivationProvider.CreateKey(pwBuffer);
            byte[] keyMaterial = WinRTCrypto.CryptographicEngine.DeriveKeyMaterial(keyOriginal, pbkdf2Parms, 32);
            ICryptographicKey derivedPwKey = keyDerivationProvider.CreateKey(pwBuffer);
            byte[] saltMaterial = WinRTCrypto.CryptographicEngine.DeriveKeyMaterial(derivedPwKey, pbkdf2Parms, 16);
            string keyMaterialString = WinRTCrypto.CryptographicBuffer.EncodeToBase64String(keyMaterial);
            string saltMaterialString = WinRTCrypto.CryptographicBuffer.EncodeToBase64String(saltMaterial);
            ISymmetricKeyAlgorithmProvider symProvider = WinRTCrypto.SymmetricKeyAlgorithmProvider.OpenAlgorithm(SymmetricAlgorithm.AesCbcPkcs7);
            ICryptographicKey symmKey = symProvider.CreateSymmetricKey(keyMaterial);
            byte[] resultBuffer = WinRTCrypto.CryptographicEngine.Decrypt(symmKey, cipherBuffer, saltMaterial);
            string result = WinRTCrypto.CryptographicBuffer.ConvertBinaryToString(System.Text.Encoding.UTF8, resultBuffer);
            return result;
        }`
And as you seen, I think that utf16_le and utf8 are the differences, is it correct? When xamarin app receives encrypted message from windows plaftorm (the code of first post) it (WinRTCrypto.CryptographicEngine.Decrypt(.,.,.))launchs the following error when it try to decrypt: "Javax.Crypto.BadPaddingException: pad block corrupted"
How could I fix this problem? Do you think that it is caused by utf6_le? or is it caused by other things? 
Thanks for your patience with me and sorry
