### ISSUE TITLE
Invalid padding issue and invalid characters in the decrypted string

### ISSUE THREAD

**Issue by kartikbb** [AArnott/PCLCrypto#122]
I am reporting two issues in one. I have upload my sample code here - [https://github.com/kartikbb/PCLCryptoSample](https://github.com/kartikbb/PCLCryptoSample)

The two issues are:

1. As you can see in my sample, I am encrypting and decrypting a string 1000 times, each time with a new password. For some iterations (approx 40%), the decryption fails with an exception - "Invalid Padding..."

2. The iterations when decryption does succeed, the resultant decrypted string has invalid characters. 

`

**Comment by AArnott** [comment]
First guess: you're probably doing something wrong with your encoding or padding or key management. Have you checked out the 'recipes' wiki page?

**Comment by AArnott** [comment]
Closing due to no response.
