### ISSUE TITLE
Exception thrown: 'PInvoke.NTStatusException' in PInvoke.Kernel32.DLL

### ISSUE THREAD

**Issue by HelenMamalaki** [AArnott/PCLCrypto#125]
Exception thrown: 'PInvoke.NTStatusException' in PInvoke.Kernel32.DLL
Additional information: NT_STATUS error: STATUS_DATA_ERROR (0xC000003E)

Hi,
I keep getting this error every so often when I try to decrypt and I have no idea what it means. When I examine the value I wish to decrypt it looks something like 꿴◃㤂㻤\u0095�뺹

I am using Encoding.Unicode.GetString and Encoding.Unicode.GetBytes to write/read the encrypted string in a file. 

The full stacktrace is below:
at PInvoke.Kernel32Extensions.ThrowOnError(NTSTATUS status)
   at PInvoke.BCrypt.BCryptDecrypt(SafeKeyHandle hKey, Byte[] pbInput, Void* pPaddingInfo, Byte[] pbIV, BCryptEncryptFlags dwFlags)
   at PCLCrypto.SymmetricCryptographicKey.Decrypt(Byte[] ciphertext, Byte[] iv)
   at PCLCrypto.CryptographicEngine.Decrypt(ICryptographicKey key, Byte[] data, Byte[] iv)
   at Myapp.filename.<Decrypt>d__13.MoveNext()

// Encryption code
```
public static async Task Encrypt(string key, string value)
        {
            byte[] dataToEncrypt = Encoding.Unicode.GetBytes(value);
            byte[] cipherText = WinRTCrypto.CryptographicEngine.Encrypt(cryptoKey, dataToEncrypt, iv);
            await LocalStorage.SaveinLocalStorage(ConstantStrings.AppName, key + ".txt", Encoding.Unicode.GetString(cipherText, 0, cipherText.Length));
        }
```
// Decryption code
```
public static async Task<string> Decrypt(string key)
        {
            string encryptedData = await LocalStorage.ReadfromLocalStorage(ConstantStrings.AppName, key + ".txt");

            // When decrypting, use the same IV that was passed to encrypt.
            byte[] plainText = WinRTCrypto.CryptographicEngine.Decrypt(cryptoKey, Encoding.Unicode.GetBytes(encryptedData), iv);
            string text = Encoding.Unicode.GetString(plainText, 0, plainText.Length);

            return text;
        }
```

**Comment by AArnott** [comment]
My best guess is you're not using the right key lengths or padding properly. But as this error comes from Win32 and not this library, I suggest you take your question to a win32 crypto forum. I'm afraid I don't have time to support all kinds of crypto bugs that a platform or calling code may have. PCLCrypto is just the middle-man here.

**Comment by HelenMamalaki** [comment]
Hi,



I copied your code from your PCLCryptoSample, (all of it apart from the
hashing bit) see below and it fails with that error on the Encrypt()
method. I can build the sample project for Windows but I am unable to run
it on a Windows device (I get TargetInvocationException).



Is there anything immediately/obviously wrong with code I copied from the
sample below?  The problem is presumably with the key creation in the first
3 lines.






// Create Key



            var asym = WinRTCrypto
.AsymmetricKeyAlgorithmProvider.OpenAlgorithm(AsymmetricAlgorithm.RsaPkcs1);

            var hash = WinRTCrypto.HashAlgorithmProvider.OpenAlgorithm(
HashAlgorithm.Sha1);

            ICryptographicKey cryptoKey = asym.CreateKeyPair(512);



// Encrypt



            var plain = Encoding.UTF8.GetBytes(value);

            var encrypted = WinRTCrypto.CryptographicEngine.Encrypt(cryptoKey,
plain);   *<-- STATUS_DATA_ERROR thrown error here*

            var encryptedString = Convert.ToBase64String(encrypted);



// Decrypt



            var encrypted = Convert.FromBase64String(encryptedString);

            var decrypted = WinRTCrypto.CryptographicEngine.Decrypt(cryptoKey,
encrypted);

            var decryptedString = Encoding.UTF8.GetString(decrypted, 0,
decrypted.Length);



I would appreciate any advice on how to correctly use this library. I am
using a PCL with Xamarin (not Forms) but I don’t think that should make a
difference?



Regards,

Helen

**Comment by AArnott** [comment]
Where does `value` come from and what is its length? It must be very short, on the order of 16 bytes or less.

**Comment by HelenMamalaki** [comment]
Hi,

The longest value I want to encrypt is around byte[54] and looks like this:
XpfZkj6mT6kxEIVxaLzIH3VhCynQzY8PN39B6r806ZO0dlRVjlEPwz

So I can't use PCLCrypto to encrypt anything bigger than byte[16]?

Originally I wanted to use the DPAPIs but PCL is missing the
Windows.Security.Cryptography (and also the System.Security.Cryptography)
namespaces.

Regards,
Helen

On 25 Apr 2017 16:08, "Andrew Arnott" <notifications@github.com> wrote:

Where does value come from and what is its length? It must be very short,
on the order of 16 bytes or less.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AArnott/PCLCrypto/issues/125#issuecomment-297061089>,
or mute the thread

**Comment by AArnott** [comment]
This is not a pclcrypto limitation, but an RSA limitation. 

You should encrypt your data with a symmetric encryption algorithm, then encrypt your symmetric key using an asymmetric algorithm.

**Comment by HelenMamalaki** [comment]
Hi Andrew,

Ok thank you for taking the time to reply. I really appreciate it. I will
research some more, SimpleAuth library might have what I am looking for
else I will follow your suggestion of encrypting the encryption key with
PCLCrypto.

Regards,
Helen
