### ISSUE TITLE
Importing public key string

### ISSUE THREAD

**Issue by AeonDave** [AArnott/PCLCrypto#127]
Hello!
How can we import a public key generated from any rsa key generator?

from my api it comes like:
`
{
"code":0,
"message":"success",
"key":"-----BEGIN PUBLIC KEY-----\r\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwnz9OS0bpl0mwOk\/2L9d\r\nJp .... 54YgkxxJA\r\nOwIDAQAB\r\n-----END PUBLIC KEY-----"}
`

I get always the error "Unexpected format or unsupported key"

Thank you

**Comment by AArnott** [comment]
Closing due to a workaround being available or lack of popular demand. This allows us to better focus on high impact issues. If you feel this is blocking you, you may add a comment here to explain why this should be prioritized.

Thank you for your understanding.
