### ISSUE TITLE
Block Length

### ISSUE THREAD

**Issue by 1036560** [AArnott/PCLCrypto#129]
Hey,

I have a question, for you! 

in this code: 
```
byte[] keyMaterial = Convert.FromBase64String(XXX);//256bits
            byte[] data = Encoding.UTF8.GetBytes("test");
            var provider = WinRTCrypto.SymmetricKeyAlgorithmProvider.OpenAlgorithm(SymmetricAlgorithmName.Aes,SymmetricAlgorithmMode.Cbc,SymmetricAlgorithmPadding.Zeros);
            var key = provider.CreateSymmetricKey(keyMaterial);
          
            var iv = WinRTCrypto.CryptographicBuffer.GenerateRandom(provider.BlockLength);
```
can we change de blockLength to 32(256 bit)?

Thx

**Comment by AArnott** [comment]
Per Wikipedia:

> Rijndael, supports block and key sizes of 128, 192, and 256 bits, but in AES the block size is always 128 bits. The extra block sizes were not adopted by the AES standard.

Also [on StackOverflow](http://stackoverflow.com/a/15436216/46926)
