### ISSUE TITLE
Xamarin Studio 5.x Nuget Client problem

### ISSUE THREAD

**Issue by zoooN** [AArnott/PCLCrypto#13]
Hi!
I have a problem with adding PCLCrypto Nuget package in XS. It says that The 'PCLCrypto 1.0.0-beta2' package requires NuGet client version '2.8.3' or above, but the current NuGet version is '2.8.1.0'. Can you solve it?

**Comment by AArnott** [comment]
I don't recall why PCLCrypto requires NuGet 2.8.3 or above -- my guess is the support for the Xamarin.iOS (unified) target.
I suggest you take this up with the Xamarin folks to update their IDE.

**Comment by jamesmontemagno** [comment]
2.8.3 in VS does add the support for unified, but 2.8.1 is what we are currently on in XS and we do plan on updating this in the future (hopefully XS 5.9). Current customers do not have access to the nuget though when using XS

**Comment by AArnott** [comment]
Thanks for chiming in @jamesmontemagno. 

Supposing PCLCrypto claimed it only required 2.8.1 of the NuGet client, I suspect it would malfunction in VS. What would XS do if it only supports 2.8.1 but the customer is using iOS Unified and tries to install the PCLCrypto package?

**Comment by AArnott** [comment]
As a workaround for folks who don't need iOS Unified support, but do want to use PCLCrypto, try installing a prior build of PCLCrypto:

    Install-Package PCLCrypto -Version 1.0.0-beta1 -Pre

**Comment by AArnott** [comment]
Another workaround is Trik's comment in #11
