### ISSUE TITLE
Android Error "Only KeyDerivationAlgorithm.Pbkdf2Sha1 is supported for this platform."

### ISSUE THREAD

**Issue by ksaye** [AArnott/PCLCrypto#130]
I am trying to convert a Windows 8 Native App to Android using Xamarin and PCLCrypto.

In Windows, I use the following:

```csharp
private static void GenerateKeyMaterial(string password, string salt, uint iterationCount, int bits, out IBuffer keyMaterial, out IBuffer iv)
        {

            // Setup KDF parameters for the desired salt and iteration count
            IBuffer saltBuffer = CryptographicBuffer.ConvertStringToBinary(salt, BinaryStringEncoding.Utf8);
            KeyDerivationParameters kdfParameters = KeyDerivationParameters.BuildForPbkdf2(saltBuffer, iterationCount);

            // Get a KDF provider for PBKDF2, and store the source password in a Cryptographic Key
            KeyDerivationAlgorithmProvider kdf = KeyDerivationAlgorithmProvider.OpenAlgorithm(KeyDerivationAlgorithmNames.Pbkdf2Sha256);
            IBuffer passwordBuffer = CryptographicBuffer.ConvertStringToBinary(password, BinaryStringEncoding.Utf8);
            CryptographicKey passwordSourceKey = kdf.CreateKey(passwordBuffer);

            // Generate key material from the source password, salt, and iteration count.  Only call DeriveKeyMaterial once,
            // since calling it twice will generate the same data for the key and IV.
            int keySize = 256;
            int ivSize = 128 / 8;
            uint totalDataNeeded = (uint)(keySize + ivSize);
            IBuffer keyAndIv = CryptographicEngine.DeriveKeyMaterial(passwordSourceKey, kdfParameters, totalDataNeeded);

            // Split the derived bytes into a seperate key and IV
            byte[] keyMaterialBytes = keyAndIv.ToArray();
            keyMaterial = WindowsRuntimeBuffer.Create(keyMaterialBytes, 0, keySize, keySize);
            iv = WindowsRuntimeBuffer.Create(keyMaterialBytes, keySize, ivSize, ivSize);
        }
```

in Android, I am using:

```csharp
private static void GenerateKeyMaterial(string password, string salt, int iterationCount, int bits)
        {
            // Setup KDF parameters for the desired salt and iteration count
            byte[] saltBuffer = WinRTCrypto.CryptographicBuffer.ConvertStringToBinary(salt, System.Text.Encoding.UTF8);
            IKeyDerivationParameters kdfParameters = WinRTCrypto.KeyDerivationParameters.BuildForPbkdf2(saltBuffer, iterationCount);

            // Get a KDF provider for PBKDF2, and store the source password in a Cryptographic Key
            IKeyDerivationAlgorithmProvider kdf = WinRTCrypto.KeyDerivationAlgorithmProvider.OpenAlgorithm(WinRTCrypto.KeyDerivationAlgorithmProvider.OpenAlgorithm(KeyDerivationAlgorithm.Pbkdf2Sha256).Algorithm);
            //IKeyDerivationAlgorithmProvider kdf = WinRTCrypto.HashAlgorithmProvider.OpenAlgorithm(HashAlgorithm.Sha256);
            //.KeyDerivationAlgorithmProvider.OpenAlgorithm(HashAlgorithm.Sha256);
            byte[] passwordBuffer = WinRTCrypto.CryptographicBuffer.ConvertStringToBinary(password, System.Text.Encoding.UTF8);
            ICryptographicKey passwordSourceKey = kdf.CreateKey(passwordBuffer);

            // Generate key material from the source password, salt, and iteration count.  Only call DeriveKeyMaterial once,
            // since calling it twice will generate the same data for the key and IV.
            int keySize = 256;
            int ivSize = 128 / 8;
            int totalDataNeeded = (int)(keySize + ivSize);
            byte[] keyAndIv = WinRTCrypto.CryptographicEngine.DeriveKeyMaterial(passwordSourceKey, kdfParameters, totalDataNeeded);

            // Split the derived bytes into a seperate key and IV
            byte[] keyMaterialBytes = keyAndIv.ToArray();
            Buffer.BlockCopy(keyMaterialBytes, 0, keyMaterial, keySize, keySize);
            Buffer.BlockCopy(keyMaterialBytes, keySize, iv, ivSize, ivSize);
        }
```
But in Android I get the error:  
> System.NotSupportedException: Only KeyDerivationAlgorithm.Pbkdf2Sha1 is supported for this platform.

Reading, it appears that SHA256 is supported on Android (Samsung Edge 7), so I am stumped.

Kevin

**Comment by AArnott** [comment]
Can you include the callstack of the exception that is thrown?

**Comment by ksaye** [comment]
Sure, line 84 is:              byte[] keyAndIv = WinRTCrypto.CryptographicEngine.DeriveKeyMaterial(passwordSourceKey, kdfParameters, totalDataNeeded);

Here is the call stack:

	0x70 in MyPasswords.MainActivity.GenerateKeyMaterial at C:\Users\ksaye\Documents\Visual Studio 2015\Projects\MyPasswords\MyPasswords\MainActivity.cs:84,13	C#
 	0x11 in MyPasswords.MainActivity.decryptData at C:\Users\ksaye\Documents\Visual Studio 2015\Projects\MyPasswords\MyPasswords\MainActivity.cs:52,13		C#
 	0x2C in MyPasswords.MainActivity.showItem at C:\Users\ksaye\Documents\Visual Studio 2015\Projects\MyPasswords\MyPasswords\MainActivity.cs:43,13			C#
 	0x3A0 in MyPasswords.MainActivity. at C:\Users\ksaye\Documents\Visual Studio 2015\Projects\MyPasswords\MyPasswords\MainActivity.cs:138,41			C#

I am happy to share the source code, but I need to change the salt.

**Comment by AArnott** [comment]
Salts are not secret. Only keys are. If your security depends on salts  being secret, you may need to review your design. 

I don't need to see more of your source code though. 

The callstack above doesn't show any PCLCrypto frames. If this is accurate, your own code would be throwing the exception.

**Comment by ksaye** [comment]
Do you have an example where you use both "SymmetricAlgorithmNames.AesCbcPkcs7" and "CryptographicEngine.Decrypt" with an iv key?

**Comment by AArnott** [comment]
yes: https://github.com/AArnott/PCLCrypto/wiki/Crypto-Recipes#perform-aes-encryptiondecryption

**Comment by AArnott** [comment]
The [v2.1.40-alpha release](https://www.nuget.org/packages/PCLCrypto/2.1.40-alpha) on nuget.org includes [some significant changes](https://github.com/AArnott/PCLCrypto/releases/tag/v2.1.40-alpha). I'm optimistic that this issue is either resolved or perhaps does not matter to you any more. Please comment if it still repros and bothers you and we can reactivate.
