### ISSUE TITLE
Provide a public API where we can export public/private keys to serialized format

### ISSUE THREAD

**Issue by gugavaro** [AArnott/PCLCrypto#131]
Would be nice to have a method that would export public/private keys in ASCII or any other convenient format that would make it easy to be copied and saved in a secured location.

**Comment by AArnott** [comment]
Closing due to a workaround being available or lack of popular demand. This allows us to better focus on high impact issues. If you feel this is blocking you, you may add a comment here to explain why this should be prioritized.

Thank you for your understanding.
