### ISSUE TITLE
UWP: Process initialization failed with status 0xc0000139

### ISSUE THREAD

**Issue by CIPop** [AArnott/PCLCrypto#137]
A very simple UWP application using SDK 16299 will fail if compiled (AOT) with the following error when the binary is loaded:
"Process initialization failed with status 0xc0000139"

Activating "https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/show-loader-snaps" then running the app in a debugger shows the following issue:

`1725 3de8:3df4 @ 00384546 - LdrpProcessWork - ERROR: Unable to load DLL: "NTASN1.dll", Parent Module: "C:\WINDOWS\SYSTEM32\ncrypt.dll", Status: 0xc0000139`

**Comment by AArnott** [comment]
This looks like a Windows OS bug to me. ncrypt.dll can't load another DLL it depends on sounds like a UWP sandboxing problem, perhaps. Not sure what PCLCrypto can do about it.

**Comment by AArnott** [comment]
This issue was moved to AArnott/pinvoke#377

**Comment by AArnott** [comment]
The workaround in PInvoke can be applied to PCLCrypto users by installing the latest PInvoke.NCrypt package into your project (in addition to PCLCrypto).
