### ISSUE TITLE
Alpha assembly causes MSBuild failure in ResolveLibraryProjectImports task

### ISSUE THREAD

**Issue by toddlucas** [AArnott/PCLCrypto#138]
I'm attempting to test the new prerelease build `2.1.17-alpha-g5b1e8dff8c` and am currently unable to due to an issue exposed in MSBuild. I've updated the [related issue](https://developercommunity.visualstudio.com/content/problem/164584/cant-build-android-error-msb4018-the-resolvelibrar.html) on the VS site, thought it's closed.

I have two Xamarin projects using the typical structure of `MyProject` as a NET Standard project and `MyProject.Android` for the native parts. If I reference the new PCLCrypto assembly in the base project, it builds fine. However, building the Android project, which references the base project, the build fails.

```
error MSB4018: The "ResolveLibraryProjectImports" task failed unexpectedly.
error MSB4018: System.NotSupportedException: The given path's format is not supported.
error MSB4018:    at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
error MSB4018:    at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
error MSB4018:    at System.IO.Directory.CreateDirectory(String path)
error MSB4018:    at Xamarin.Android.Tools.Files.ExtractAll(ZipArchive zip, String destination, Action`2 progressCallback, Func`2 modifyCallback, Func`2 deleteCallback, Boolean forceUpdate)
error MSB4018:    at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(DirectoryAssemblyResolver res, ICollection`1 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
error MSB4018:    at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
```

Running VS 2017 Community 15.6.2. I'm not sure if this is technically your issue. It will make it hard to test for some people, though. Thanks!

**Comment by AArnott** [comment]
Thanks for reporting. I'll see if I can figure out what's going on here and perhaps help push for the bug to be reconsidered.

**Comment by AArnott** [comment]
I see you filed [a new feedback ticket](https://developercommunity.visualstudio.com/content/problem/218603/msbuild-failure-in-resolvelibraryprojectimports-ta.html). Thanks.

**Comment by jonathanpeppers** [comment]
So there is definitely a Xamarin.Android issue here.

If I look at `__AndroidLibraryProjects__.zip` inside your `monoandroid23\PCLCrypto.dll` assembly, it has crazy paths inside the zip file:
```
Archive:  __AndroidLibraryProjects__.zip
Zip file size: 1939 bytes, number of entries: 7
-rw-rw-rw-  2.0 unx       39 b- defN 18-Mar-10 10:12 library_project_imports/__res_name_case_map.txt
drwxrwxrwx  2.0 unx        0 b- stor 18-Mar-10 10:12 library_project_importsC:/projects/pclcrypto/src/.obj/pclcrypto/Release/monoandroid23/jl/assets/
drwxrwxrwx  2.0 unx        0 b- stor 18-Mar-10 10:12 library_project_importsC:/projects/pclcrypto/src/.obj/pclcrypto/Release/monoandroid23/jl/bin/
drwxrwxrwx  2.0 unx        0 b- stor 18-Mar-10 10:12 library_project_importsC:/projects/pclcrypto/src/.obj/pclcrypto/Release/monoandroid23/jl/java/
drwxrwxrwx  2.0 unx        0 b- stor 18-Mar-10 10:12 library_project_importsC:/projects/pclcrypto/src/.obj/pclcrypto/Release/monoandroid23/jl/res/
drwxrwxrwx  2.0 unx        0 b- stor 18-Mar-10 10:12 library_project_importsC:/projects/pclcrypto/src/.obj/pclcrypto/Release/monoandroid23/jl/res/values/
-rw-rw-rw-  2.0 unx      128 b- defN 18-Mar-10 10:12 library_project_importsC:/projects/pclcrypto/src/.obj/pclcrypto/Release/monoandroid23/jl/res/values/strings.xml
7 files, 167 bytes uncompressed, 117 bytes compressed:  29.9%
```
This zip is included as an `EmbeddedResource`--this is how Android stuff gets packaged up.

When developers try to consume this assembly, the build fails on their end because `System.IO` will throw if it sees these paths containing `:`. The paths are also completely wrong!

Xamarin.Android is definitely at fault, since I can clone this Github repo, build with `msbuild src /restore /bl /t:build,pack`, and see the same incorrect behavior on VS 15.7.3.

To get a full fix for this, I'll have to:
- Get a fix in Xamarin.Android (maybe on both sides: library build, and consumer of the library)
- Send a PR for a workaround (if there is one) for @AArnott , so that he can keep shipping out of AppVeyor. It looks like AppVeyor is currently using VS 15.5.4 looking at the build log.

**Comment by jonathanpeppers** [comment]
@AArnott can you change these to use Windows path separators?

https://github.com/AArnott/PCLCrypto/blob/f9504f256c16c3fb4b5fb312b200975c40f93f9a/src/Directory.Build.props#L4-L5

It's causing these paths to get passed into a Xamarin.Android MSBuild task:
![image](https://user-images.githubusercontent.com/840039/41563590-a5be0272-7315-11e8-9b33-fd36928fdb58.png)

That will fix your build, and you won't have to wait on a Xamarin.Android release.
