### ISSUE TITLE
use pclcrypto in a webapp

### ISSUE THREAD

**Issue by waywer** [AArnott/PCLCrypto#144]
hey, 
I installed pclcrypto to use in a webapp. It seems to work but when I debug the deal won't be availible on my website. Usually this will be done by including the library in the package.json but is seems this isn't working. So i was wondering, is pclcrypto useable for a webapp or only useable for apps.

**Comment by AArnott** [comment]
It will work for web apps too. But why are you using package.json? Do you mean project.json? And even if so, project.json is a deprecated technology that I am not testing with any more. Can you use PackageReference?

Also, what platform are you targeting with your web app?

**Comment by waywer** [comment]
Tahnk you for your responce . I m using a little bit old technologies were i don't have any influence on. I think it project.json and package.json are the same. I m currently building a ddn8 module. 

I just started to make it work again and i looks like grunt doesn't know that PclCrypto is used and don't copy the dll to my website. I will keep you updated if i find a solution

**Comment by waywer** [comment]
i feel very stupid. The problem was that the dll weren't moved to the website. This was caused by nuget. Nuget installed the libary in a map called bin. This map wasn't included in the gruntfile (DebugbinsToSite part). When i included this map, it worked perfectly
