### ISSUE TITLE
PCLCrypto does not support .NET 3.5

### ISSUE THREAD

**Issue by clarissss** [AArnott/PCLCrypto#147]
Hi, I was going to install PCLCrypto v2.0.147 but it's giving me an error saying 'could not install package'
> Could not install package 'PCLCrypto 2.0.147'. You are trying to install this package into a project that targets '.NETFramework,Version=v3.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by AArnott** [comment]
That's because evidently you're targeting .NET 3.5, and this library targets net45.
