### ISSUE TITLE
wpf and windows form?

### ISSUE THREAD

**Issue by fastlater** [AArnott/PCLCrypto#148]
I know that the main targe of this library is xamarin but it could work without problems or bugs in a wpf and/or windows form project? Will it work on projects with higher target frameworks like 4.6 or 4.7, or it will work in 4.5 only? 
I hope I can use pclcrypto for all kinds of C# projects. Thanks in advance.

**Comment by AArnott** [comment]
> the main targe of this library is xamarin

That's just two of the targets. It supports .NET Framework (and somewhat supports .NET Core) as well. 
Yes, it will work on WPF/WinForms projects of any .NET Framework version that NuGet will install the package for.

Indeed, its intent is to allow you to write crypto code once and compile it for every possible platform.
