### ISSUE TITLE
native exception "Entrypoint not found" when running in UWP x64

### ISSUE THREAD

**Issue by gentledepp** [AArnott/PCLCrypto#149]
Tested with latest versions v2.1.32-alpha and v2.1.27-alpha

Reproduce:
Create an UWP project.
Reference PCL Crypto
Build in release mode (or debug mode) and enable .net native toolchain (latest uwp package Microsoft.NETCore.UniversalWindowsPlatform 6.2.8)

App launches and crashes immediately with "Entrypoint not found" written to the output.

`The program '[12320] Some.App.UWP.exe' has exited with code -1073741511 (0xc0000139) 'Entry Point Not Found'.`

We solved this by switching to the .NET Standard implementations of SHA256 and 512.
So this is just a reminder!

**Comment by AArnott** [comment]
Did you have to add any actual *use* of pclcrypto to the project as part of this repro? 
I can't imagine how a bug in PCLCrypto would cause the entire app to fail to launch with that error unless it was a bug in the .NET Native toolchain.

**Comment by gentledepp** [comment]
Yes, we did use PCLCrypto - we have our onw .NET Standard 2.0 based library which caluclates some hashes using sha256 and sha512. This still works like a charm on .net462, android and ios.
Interestingly though, the crash happens without touching this code, as it is right at the start of the startup process.

Also, we could reproduce this with an empty UWP app with just a packagereference to pclcrypto. Not even a using statement is referring to it.

So if you are not embedding any native code in PCLCrypto, I am certain that this is a bug in the .net native toolchain and you can close this issue. (I had no time to go through your code - sry)
It might help some other poor fools that dare to create UWP apps though...

**Comment by AArnott** [comment]
Thanks for the report. I'll reach out to the native toolset folks.

**Comment by AArnott** [comment]
The [v2.1.40-alpha release](https://www.nuget.org/packages/PCLCrypto/2.1.40-alpha) on nuget.org includes [some significant changes](https://github.com/AArnott/PCLCrypto/releases/tag/v2.1.40-alpha). I'm optimistic that this issue is either resolved or perhaps does not matter to you any more. Please comment if it still repros and bothers you and we can reactivate.
