### ISSUE TITLE
Error "Unexpected format or unsupported key" when importing keys

### ISSUE THREAD

**Issue by rouacke** [AArnott/PCLCrypto#150]
One of our unit tests fails intermittently. Among other things, the test in question generates a private key, exports the key, and imports the key. The relevant code looks something like this:

```
IAsymmetricKeyAlgorithmProvider provider = AsymmetricKeyAlgorithmProvider.OpenAlgorithm(AsymmetricAlgorithm.RsaSignPkcs1Sha256);
ICryptographicKey key1 = provider.CreateKeyPair(2048);
byte[] keyBytes = key1.Export();
ICryptographicKey key2 = provider.ImportKeyPair(keyBytes)
```

Every once in a great while (like, once every few months), the import fails with the following exception:

```
System.NotSupportedException : Unexpected format or unsupported key.
  ----> System.FormatException : Unexpected format or unsupported key.
   at PCLCrypto.Formatters.KeyFormatter.TrimOrPadZeroToLength(Byte[] buffer, Int32 desiredLength)
   at PCLCrypto.BCryptRsaKeyFormatter.WriteCore(Stream stream, RSAParameters parameters)
   at PCLCrypto.Formatters.KeyFormatter.Write(Stream stream, RSAParameters parameters, Boolean includePrivateKey)
   at PCLCrypto.NCryptAsymmetricKeyProviderBase.ImportKeyPair(Byte[] keyBlob, CryptographicPrivateKeyBlobType blobType)
  ...
```

We haven't been able to reproduce. However, we did change the test to log the failing keys. Here's an example, base64-encoded:

```
MIIEyAIBADANBgkqhkiG9w0BAQEFAASCBKMwggSfAgEAAoIBAQDRzWS6wDPYVUvvTksKEFTGPAeRo6wVau3J8yiLHYbQE85kPRuNtKhpw0ZRs1qubQx+itTW6OvTGTII8XgGCXzcXYqT65TwKPlGpVagnthnn0Ro6AZdzqnazOYJCEQUSwig68m7O53u2lk0KAxa2a7BmJUBSfk7D42nlKIkTwszbz1suQhagO42CIifOfdzA7TZHZRozQuP48L1jZBZuMWqtoR1vHs4M3AMf5XGVi2NetvImAAvWI2OMMu7ksCPGD84u3NYHXrCbFrywtSdVWHTnT4A9HckRq1rkQL16nJXn4TXNRcMk+g+RBGdSdSzRE7ZoYZNtk+2U5QQ2MzjZ28rAgMBAAECgf8ADLs8/dMMUs33mgueJVk3wUC6nJEuNCrGIgczW9N3L4i0Ewp98oK7X81pm1HZ/eALapabw3OvEh/qIPTTSo5u6GcRyNqYzLOkcv8vJGG3vRORP9FJ+jOvZPhj2OWEEaaOYXVs3Jw54hOx/wE6MjwKCekfE6y99zmRzxF3mTb9WGJZKwxcvv+wc7OD8tja/7+BCqV8W1pIPU8fB0jBya6FXDuQOeiZ+jTnExLLc7Xy+VqqTmuA5BfFx22REnh2PSbGOJQBEYbSpMsBUS1JVNw5vX1mw1ckpgneVl53oVpaERUe261LrC1MLKpTbo0TfiypjJRqL7QHTVxAvulB5DECgYEA5Ci3EBsN+V/kd7hyHJHTKwy2dwe26QbZk7UlA1QgZFHVZqjffL4zfHq/+cSObgOJ53D1yoIESzlh05ZinddecutEYIZ74uS9ckFmM6Z8/8YqPo+Kak9T8K6iZlb0jLIdFt70zWoLchhMJRajeOXED4fllxFUhOjIHOfxeybvSRECgYEA62c/LBZCbhzqzPs6t5zgwUr+QWjnYQfjXhWAl/nNbuFctlnnBEygYSlauNBEfYzb6ZlbQmJnS9Kogw7wxazNRWd1yQlrRZ8rSWn3snIeKVdEEpl4uPT3yymxsIUT4c0kGqqoryvYP+gZ4BuUEnV0rR0KjpyT8Q0xVQRQAAEaFHsCf3aIsJKte5UTPJ72NFKjcBHtiN5OI7js1hzm/1O7YRi9ayDqmzEzn4wMObCJbXW6YOrcxNVwtspeBXTnrFRUj70kfWGofLRkIgg58d7joA1B5rCZ4k9Y50Mjdzuz8VknL/Wx33zYmxmrheO+3y7wL+vhrmXNmxtx1IUv+0T/9VECgYEAvX67Z63zg9hbWu7R8YSjmHXZ/qWHvKAw80ez4KMCMEPR8iikwt08LXqwwR1GRRri3ETLJcE5DdxiMj4Qq8/S3g/OzSp74+uhWNOoxUj/5p+M+Lv6ZkksP6ssksBNpPMSITVH3NsalTctvS32IHXUmpZKLUr1/JF2KM3z6Ez6xYkCgYBEva17GOHRy0fuReQjn8FuTNhG/Mkbb01AlgNvzquLXDC2VmQ7Oak7ez/TvzpTeYWkfLcVqxVVBStBxS58oIprJ+bh7X1fccSz6dI87tYv3iXTbbM+z6ZkvKy8Ilb7c1eQpu0D+lJ8zzrlq+98/JL4mrJEL5SL/68qafnXMxtmiKANMAsGA1UdDzEEAwIAEA==
```

This key was generated using code similar to the code above. It fails to import. As far as I can tell, the key itself looks fine. OpenSSL doesn't seem to see a problem with it. 

We're using version 2.1.32-alpha. The problem occurred in prior versions as well.

The project targets .NET Framework 4.7.2.

**Comment by AArnott** [comment]
Thanks for the great report and inclusion of all the detail I suspect would be necessary to track down the problem. We've had bugs like this in the past and it often has to do with zero padding issues, which are a real pain because various APIs have conflicting requirements regarding padding.

I imagine we could fix this, but now that .NET Core is mature and has cryptography APIs, I've deprioritized any work on this since a Microsoft-supported API that works cross-platform is available.

**Comment by rouacke** [comment]
Thanks for the reply. I suspected as much. Appreciate your hard work.

**Comment by AArnott** [comment]
The [v2.1.40-alpha release](https://www.nuget.org/packages/PCLCrypto/2.1.40-alpha) on nuget.org includes [some significant changes](https://github.com/AArnott/PCLCrypto/releases/tag/v2.1.40-alpha). I'm optimistic that this issue is either resolved or perhaps does not matter to you any more. Please comment if it still repros and bothers you and we can reactivate.

**Comment by rouacke** [comment]
Thanks for the followup. Retested with the key above. Unfortunately, the import still fails. This is the error:

```
  Message: 
    System.NotSupportedException : Unexpected format or unsupported key.
      ----> System.FormatException : Unexpected format or unsupported key.
  Stack Trace: 
    KeyFormatter.TrimOrPadZeroToLength(Byte[] buffer, Int32 desiredLength)
    CapiKeyFormatter.NegotiateSizes(RSAParameters parameters)
    RsaAsymmetricKeyAlgorithmProvider.ImportKeyPair(Byte[] keyBlob, CryptographicPrivateKeyBlobType blobType)
    SigningTests.TestFailedSigningKey2() line 111
    --FormatException
    KeyFormatter.FailFormat(String message)
    KeyFormatter.TrimOrPadZeroToLength(Byte[] buffer, Int32 desiredLength)
```

For the record, this is the code that produces the error:

```
string encoded = "...base64 encoded key...";
byte[] bytes = Convert.FromBase64String(encoded);

var provider = AsymmetricKeyAlgorithmProvider.OpenAlgorithm(AsymmetricAlgorithm.RsaSignPkcs1Sha256);

using (ICryptographicKey key = provider.ImportKeyPair(bytes))
{
    // Do nothing.
}
```

My _assumption_ is that the problem is on the import side, that the key itself is fine. As noted, I tested the key with OpenSSL, which didn't report any problems. It's possible that OpenSSL is too forgiving (or that I just don't know what I'm doing).

This isn't a big issue for us. The problem occurs infrequently. We can test the generated key to ensure that it can be imported. Eventually, we'll migrate to the .NET Standard APIs.

Thanks again for all your work. Appreciate it.
