### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by badhitman** [AArnott/PCLCrypto#151]
1. go [here](https://github.com/aarnott/pclcrypto#donations) first
2. and try clicking on the link **[donating cash or bitcoins](https://www.coinbase.com/checkouts/b3affe1c4e7b7b60028c3efcce2b1931)**

> Page not found
> 
> Sorry we couldn't find what you were looking for.
> Back to Coinbase

**Comment by AArnott** [comment]
Thanks for noticing. Fixed by 3325b159a5a52017fc20f339eeef296226c1403b.
