### ISSUE TITLE
Need to add uap10.0.17763 target to PCLCrypto

### ISSUE THREAD

**Issue by AArnott** [AArnott/PCLCrypto#152]
6 UAP tests in the solution throw NotImplementedByReferenceAssemblyException because UAP consumes the netstandard2.0 build of the library instead of a build of the library that contains UAP-specific code.

See https://github.com/novotnyllc/MSBuildSdkExtras/issues/237 for tracking issue.

**Comment by 1Cor125** [comment]
Any update on this issue @AArnott ? We are looking forward to taking the 2.1 update on an app we have that runs on Android, iOS and UWP. Currently we have branching logic on the UWP since the OOB dotnet crypto is actually a little faster than the WinRT implementation.

**Comment by AArnott** [comment]
> the OOB dotnet crypto

What is that? 

I haven't had time to spend on it yet. Not likely to for the next month or so either.
I will say that targeting uap is often problematic. So if you'd like to try your hand at it, you're welcome to it if it's simple. If it's a lot of code changes, I think we should wait till my `renovate` branch merges to avoid a lot of merge conflicts.

**Comment by 1Cor125** [comment]
Sorry @AArnott , by "OOB dotnet crypto", I meant the out of the box `System.Security.Cryptography` API that is included in the netstandard2 contract. 

I will check out `main` and see if I can get my bearings. Thanks.
