### ISSUE TITLE
Sporadic NotImplementedException on some environments

### ISSUE THREAD

**Issue by akrobet** [AArnott/PCLCrypto#18]
Hi 
I've been struggling to figure out the reason why some of our environments sometimes (not always!) fail with a "System.NotImplementedException: Not implemented in reference assembly." exception.

Our solution has a .net 4.5 backend, silverlight 5 client and portable classes. I've installed PCLCrypto into all relevant projects (both backend, client, and portable) via NuGet. 

It works fine locally and sometimes also on our production and acceptance environment, but then after a deployment it can be broken again.. 

I've created a helper class in a common portable project, that has the following code:

```
public static byte[] EncryptAes(byte[] data, string encryptionKey)
        {
            byte[] salt = Encoding.UTF8.GetBytes(encryptionKey);
            byte[] key = CreateDerivedKey(encryptionKey, salt);

            ISymmetricKeyAlgorithmProvider aes = WinRTCrypto.SymmetricKeyAlgorithmProvider.OpenAlgorithm(SymmetricAlgorithm.AesCbcPkcs7);
            ICryptographicKey symetricKey = aes.CreateSymmetricKey(key);
            var bytes = WinRTCrypto.CryptographicEngine.Encrypt(symetricKey, data);
            return bytes;
        }

        public static byte[] CreateDerivedKey(string encryptionKey, byte[] salt, int keyLengthInBytes = 32, int iterations = 1000)
        {
            byte[] key = NetFxCrypto.DeriveBytes.GetBytes(encryptionKey, salt, iterations, keyLengthInBytes);
            return key;
        }
```

I get the error at `NetFxCrypto.DeriveBytes.GetBytes`

I can see that the right dlls are referenced and included in the bin folder. I'm out of ideas as of what can cause this behaviour. Any suggestions to try?

**Comment by AArnott** [comment]
Verify that however you are deploying it actually packages up the
implementation assembly rather than the reference assembly. That's the only
thing that can go wrong AFAIK.
You might try installing this NuGet Package as well:
https://www.nuget.org/packages/SuppressPackagingPclFacades/

It is supposed to make doubly sure that only the platform assembly is
deployed.

**Comment by akrobet** [comment]
I am not sure how to identify the reference assembly.. the dll that is included in the deployed solution is from the lib/net40-Client folder for the backend and lib/sl5 for the client. 
I've tried to install the NuGet package you're referring to, but I get
`
Could not install package 'SuppressPackagingPclFacades 1.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but th
e package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
`

I'v also tried to host the same deployment that doesn't work on the server, locally, on my machine, and it worked fine!! So it must be a machine/OS/.Net framework related issue imo..?

**Comment by AArnott** [comment]
It sounds like the SuppressPackagingPclFacades package could use an update. On the other hand, it's not supposed to be necessary any more.
Yes, as long as you're getting the assembly from a folder that doesn't start with "portable-" you should be fine. And it sounds like that's what you've already ensured.
Does your server have the assembly in its GAC? If so, try removing it as that would always "win", and make you 'lose'.

**Comment by AArnott** [comment]
Closing due to no response. But I hope that one of my recent suggestions has helped you out.
