### ISSUE TITLE
Worked on Xamarin.Mac 1.xx and now fails with Xamarin.Mac 2.0x

### ISSUE THREAD

**Issue by ghost** [AArnott/PCLCrypto#19]
Hi,

We were using the lib with unified Xamarin.Mac 1.xx and now fails with Xamarin.Mac 2.0x. I've tried to add support for Xamarin.Mac 2.0x however am experiencing difficulties. Are you able to add support?

Thanks,

Helen

**Comment by AArnott** [comment]
I am no longer a paying subscriber of Xamarin software, so I doubt my dev tools allow targeting Xamarin.Mac 2.0.
But I'll accept a pull request that works. :)

**Comment by YumiFuze** [comment]
Sure, happy to do so but will need guidance... I had a go but don't understand how you built the solution. Any tips on how to add for Xamarin.Mac 2.0 ?

**Comment by YumiFuze** [comment]
Okay ... I'm not familiar with StyleCop however got it to compile successfully for Xamarin.Mac 2.0. I've also added the Mac dll to the project and it runs.

When I've got a bit more time, I'll sit down and get it to play nicely with StyleCop and push it.

**Comment by AArnott** [comment]
Great.

Sent from my Windows Phone

-----Original Message-----

**Comment by lextm** [comment]
@AArnott Since this remains an open source project, you should request open source licenses from Xamarin, http://resources.xamarin.com/open-source-contributor.html to ensure this library works fine on those platforms.

**Comment by AArnott** [comment]
Ooh! I didn't know about that. Thank you for sharing!

**Comment by AArnott** [comment]
Hmmm... So I have the latest Xamarin software but I don't see anything in the VS integration about Mac 2.0 support. I don't know how to add it. Any suggestions?

**Comment by lextm** [comment]
http://blog.xamarin.com/unified-api-with-64-bit-support-for-ios-and-mac/

So-called 2.0 in fact means unified API based new project. So you can create new projects in VS and then migrate the code.

**Comment by AArnott** [comment]
Hmm.. are you saying that Mac 2 support is simply the iOS-Unified target platform? PCLCrypto already supports that. What more do we need to do?

**Comment by lextm** [comment]
Not iOS Unified, but Mac Unified. I made a mistake above by saying "create new projects in VS", as Xamarin.Mac projects can only be created on OS X with Xamarin Studio at this moment. 

If you try to create a new project there in Xamarin Studio (on OS X), you will see the wizard for Classic API (Xamarin.Mac 1.0), as well as for Unified API (Xamarin.Mac 2.0).

**Comment by AArnott** [comment]
I see. Then I'll have to wait a few more days to regain access my mac mini. Are one of these Mac-Unified projects a class library?
And do you have any idea what the target framework name is for mac 2 in nuget terminology?

**Comment by AArnott** [comment]
Ah, I see that [this blog post](http://blog.xamarin.com/how-to-update-nuget-packages-for-64-bit/) explains it. Thanks.

**Comment by AArnott** [comment]
So a Xamarin engineer reports that this isn't a PCLCrypto bug at all, but rather a Xamarin issue which has been fixed, although it may not be in publicly released form yet.

More info: https://forums.xamarin.com/discussion/40997/system-servicemodel-dll-and-xm-4-5-profile#latest
