### ISSUE TITLE
Compatibility with Xamarin.iOS Unified API

### ISSUE THREAD

**Issue by gabrieligbastos** [AArnott/PCLCrypto#2]
Hi Arnott,

First of all, I would like to congratulate you for this project. It is pretty good and worked like a charm. There is only one thing, I just updated my Xamarin.iOS projects to the Unified API. And now, it lost compatibility with the Touch project, because the new Unified API, is not being recognized in the Nuget file.

Do you have any plan for fix those changes?

Thanks in regard,

**Comment by AArnott** [comment]
This appears to be what pull request #3 resolves.

**Comment by gabrieligbastos** [comment]
Yeah perfect.. That is exactly what #3 will resolve...

Sorry, I didnt have any code to pull because I dont know how nuget projects works. But just folkowing the changes over there and learning.. ;)

Thanks very much AArnott. If you want can close here and I will follow the other issue..

Thans again,
Gabriel
