### ISSUE TITLE
Windows phone 8.1 IHashAlgorithmProvider CreateHash not supported

### ISSUE THREAD

**Issue by psdao1102** [AArnott/PCLCrypto#20]
Im not sure if this is intended or a bug. When i call my PCL library from a windows phone 8.1 silverlight application(both with PCLCrypto referenced) and IHashAlgorithm.CreateHash() or HashData(..) is called a Specified method is not supported exception. 
Current Example:

    var mac = WinRTCrypto.HashAlgorithmProvider.OpenAlgorithm(alg);
    var keyMaterial = WinRTCrypto.CryptographicBuffer.ConvertStringToBinary(key, System.Text.Encoding.UTF8);

    var hashBin = mac.HashData(keyMaterial);
    var hash = WinRTCrypto.CryptographicBuffer.EncodeToHexString(hashBin);
    return hash;

Is this intended? and if so how do i get around this problem?

**Comment by AArnott** [comment]
We have tests and apps that demonstrate this is working. Did you install the NuGet package to both projects? I see you mentioned that both reference PCLCrypto, but do they reference it via a NuGet package install into both projects or something manual?

If you want to reactivate the bug, please include the exception message and callstack.
