### ISSUE TITLE
CFB128-AES-128 is not supported

### ISSUE THREAD

**Issue by lextm** [AArnott/PCLCrypto#21]
I am working on #SNMP Library (https://github.com/lextm/sharpsnmplib) and just tried out PCLCrypto.

I can see three of the four required by SNMP v3 protocol are supported,
* MD5
* SHA-1
* CBC-DES
The only missing piece is [CFB128-AES-128](https://tools.ietf.org/html/rfc3826#page-5).

This seems to be a limitation coming from [Windows Runtime](https://msdn.microsoft.com/en-us/library/windows.security.cryptography.core.symmetricalgorithmnames.aspx) So I am just opening the issue to remind others. There is no urgent need (at least for #SNMP Library) to fix it.

**Comment by AArnott** [comment]
Lack of support in the WinRT need not prevent us from supporting it in PCLCrypto for those platforms that do support it. 

However if we don't have contributions nor further interest in this algorithm being supported expressed within a few weeks, we'll probably close this issue pending further desire to fix it.

**Comment by YumiFuze** [comment]
This might help: http://www.bouncycastle.org/csharp/

**Comment by AArnott** [comment]
Thanks, @YumiFuze. That might help others looking for a solution across platforms, but PCLCrypto won't be using that. BouncyCastle's approach is a new, software implementation of crypto. But PCLCrypto's approach is a portable API to invoke crypto in the platform.
