### ISSUE TITLE
PBKDF2 always uses HMAC-SHA1

### ISSUE THREAD

**Issue by myfreeweb** [AArnott/PCLCrypto#25]
Key derivation on platforms other than WinRT [currently uses Rfc2898DeriveBytes](https://github.com/AArnott/PCLCrypto/blob/master/src/PCLCrypto.Shared.NetFx/CryptographicEngine.cs#L99) which is hardcoded to use PBKDF2-HMAC-SHA1. So the algorithm I specified (`OpenAlgorithm(KeyDerivationAlgorithm.Pbkdf2Sha256)`) is *silently* ignored!

**Comment by AArnott** [comment]
At a minimum, I'll fix PCLCrypto to not silently ignore when these other algorithms are passed in, but rather throw a `NotSupportedException`. If you are aware of how to support these other algorithms on .NET or other non-WinRT platforms, please let me know.

**Comment by julian-r** [comment]
Seems like, this is still open. Here it always uses sha1
```
            int iterations = 77000;
            byte[] password = Encoding.UTF8.GetBytes("Hello123");
            byte[] salt = Convert.FromBase64String("3ND3wDJfeBsukz0kB6p549jtJLu0a6MbYIG9Yeev2iA=");

            IKeyDerivationAlgorithmProvider provider = WinRTCrypto.KeyDerivationAlgorithmProvider.OpenAlgorithm(KeyDerivationAlgorithm.Pbkdf2Sha384);
            IKeyDerivationParameters pas = WinRTCrypto.KeyDerivationParameters.BuildForPbkdf2(salt, iterations);
            ICryptographicKey keyOrig = provider.CreateKey(password);

            byte[] key = WinRTCrypto.CryptographicEngine.DeriveKeyMaterial(keyOrig, pas, 32);

            Console.WriteLine(Convert.ToBase64String(key));
            Console.ReadLine();
```
Version 1.0.2.15130 from nuget

**Comment by AArnott** [comment]
@julian-r You say you're using 1.0.2.15130, but this issue is fixed in the 1.0.3 milestone, so you aren't using the version with the fix (which hasn't been published to nuget yet)

**Comment by AArnott** [comment]
I've just published the 1.0.80 version and renamed the milestone to match.

**Comment by julian-r** [comment]
Tank you very much!

Just asking, if there is another way to do a Pbkdf2Sha512 on Android with PCL crypto?
Or do I have to go with BouncyCastle or do I have to install the bouncycaste jar into the project to make the algorithm available. I tried to look into the source but I can't find any Android specifics.

**Comment by AArnott** [comment]
That depends on whether Android already has Pbkdf2Sha512 built-in. If it does, PCLCrypto can/should support it. If it doesn't, then you'll need to look at other crypto implementations. PCLCrypto does not implement crypto -- it merely invokes the crypto in the platform if it exists.
