### ISSUE TITLE
MD5 not supported in Silverlight

### ISSUE THREAD

**Issue by PavelSafronov** [AArnott/PCLCrypto#28]
MD5 is not supported by the library in Silverlight ([relevant lines of code](https://github.com/AArnott/PCLCrypto/blob/master/src/PCLCrypto.Shared.NetFx/HashAlgorithmProvider.cs#L129)). Is there a specific reason for this?

**Comment by AArnott** [comment]
No. If Silverlight supports MD5, please send a pull request to add support for it (and ensure it has an accommodating test would be great).

**Comment by AArnott** [comment]
I just confirmed that Silverlight does not have MD5 accessible to it. While we could copy an implementation of MD5 into this library, that would deviate from the position that PCLCrypto does not *implement* these algorithms, but simply provides access to whatever the platform offers. 
I might be flexible on this if there is sufficient demand. But my position at this point is Won't Fix.
