### ISSUE TITLE
Padding problems

### ISSUE THREAD

**Issue by francisrath** [AArnott/PCLCrypto#30]
I have an application where the server runs on ASP.NET and encrypts content for a Windows 8.1 / RT client. It generally works, but some files throws an `ArgumentException` with the message `Length does not a multiple of block size and no padding is selected. Parameter name: data`.

The weird thing is that I am using a cipher with padding (well, at least I think I do).

Here is my shared code with my private bits redacted:

```C#
 public class CryptoService : ICryptoService
    {
        private const string Password = "xxxxxxxxxxxxxxxxxxxxxxx";
        private static readonly byte[] Salt = Convert.FromBase64String("xxxxxxxxxxxxxxxxxxx==");
        private const int SaltSize = 16;

        public byte[] Encrypt(byte[] data, string password)
        {
            return WinRTCrypto.CryptographicEngine.Encrypt(GetKey(password), data, Salt);
        }

        public byte[] Decrypt(byte[] encryptedData, string password)
        {
            return WinRTCrypto.CryptographicEngine.Decrypt(GetKey(password), encryptedData, Salt);
        }

        static ICryptographicKey GetKey(string id)
        {
            const int Iterations = 5000; // higher makes brute force attacks more expensive
            var key = NetFxCrypto.DeriveBytes.GetBytes(id + Password, Salt, Iterations, SaltSize);

            var aesKey = WinRTCrypto.SymmetricKeyAlgorithmProvider
          .OpenAlgorithm(SymmetricAlgorithm.AesCbcPkcs7)
          .CreateSymmetricKey(key);

            return aesKey;
        }
    }
```

Any feedback on what I could be doing wrong is much appreciated :smile:

**Comment by AArnott** [comment]
I agree, based on your code you've selected `AesCbcPkcs7` which includes Pkcs7 padding. Does this exception throw on all platforms or just some of them?

BTW, it ain't a salt if it's hard-coded. I see you seem to have hard-coded it, so it's 100% worthless. Your hard-coded password is worthless too if it's shared with your client app that you ship to customers.
