### ISSUE TITLE
Add Windows 10 support

### ISSUE THREAD

**Issue by zumicts** [AArnott/PCLCrypto#32]
After referencing installing on the PCL project and Windows 10 app, I get `Not implemented in reference assembly.`.  Seems the bait and switch is not working properly.

**Comment by AArnott** [comment]
I can't repro this. When I add PCLCrypto 1.0.2.15130 into a UWP application project, the platform-specific assembly is copied to the bin directory. Please add detail to your repro if it still fails for you.

**Comment by zumicts** [comment]
Yeah, it appeared to be reference (swapped) correctly.

I wrote a helper class (PCL) using SHA1 hashing function and then called it from the UWP app but running it caused the not implemented exception.

**Comment by AArnott** [comment]
I see. So you actually had a PCL in your solution, and both your PCL project and your application project installed the PclCrypto package?

**Comment by AArnott** [comment]
It seems to work for the upcoming v1.1 version.
