### ISSUE TITLE
HashAlgorithm.Sha512 System.NotImplementedException Windows Phone 8.1 ARM

### ISSUE THREAD

**Issue by MarcMagnin** [AArnott/PCLCrypto#39]
Hey !

Thanks for this awesome library !!
I want to use the WinRTCrypto.HashAlgorithmProvider.OpenAlgorithm(HashAlgorithm.Sha512); but I get a NotImplementedException (when used on Windows Phone 8.1 ARM build).
Is there is any plan to implement this algorithm ?

Thumbs up !
Marc

**Comment by AArnott** [comment]
Is this a Wp81 (Silverlight) or wpa81 (XAML) application?
Is System.Security.Cryptography.SHA512 available in the phone application itself?

**Comment by MarcMagnin** [comment]
Thanks for the response !
it is a wpa81 (XAML) app and I can't find the System.Security.Cryptography
:/

2015-10-08 16:22 GMT+02:00 Andrew Arnott <notifications@github.com>:

**Comment by AArnott** [comment]
Did you install the PclCrypto nuget package into the wpa81 project itself as well?

**Comment by MarcMagnin** [comment]
Yes it was. I'll give another bash soon to confirm.

2015-10-08 18:47 GMT+02:00 Andrew Arnott <notifications@github.com>:

**Comment by MarcMagnin** [comment]
I can confirm. This Exception is only for ARM (on the device). No problem for x86 emulator.

**Comment by AArnott** [comment]
Then my guess is it's an issue with which DLL ships in the package for your app. I'm not sure how to best mitigate this other than depend on some NuGet v3 specific behavior, which I may end up doing.

**Comment by MarcMagnin** [comment]
Cheers. Is this what might sort it ? : http://dontcodetired.com/blog/post/Creating-a-Windows-Store-App-NuGet-Package-for-ARM-x86-and-x64.aspx

**Comment by AArnott** [comment]
That works for NuGet v2, but if this is truly an issue with the bait and switch trick just not working on NuGet v2, I think I'd rather fix it by requiring NuGet v3. Would that be a problem for you? (If you aren't using vs2015, it probably would be a problem).

**Comment by MarcMagnin** [comment]
Cheers! Absolutly not, all my computers are running VS2015.

**Comment by AArnott** [comment]
In 78a26584, I make the error of a reference assembly at runtime easier to detect.

**Comment by AArnott** [comment]
I cannot repro this. Maybe this is fixed in 1.1 or maybe it's just the less than 100% determinism behind how nuget v2 or msbuild chooses which dll's to copy into the app package. 
If this still is unreliable, let me know and that will be more incentive to switch to nuget v3 packaging.
