### ISSUE TITLE
Duplicate types in Abstractions

### ISSUE THREAD

**Issue by onovotny** [AArnott/PCLCrypto#4]
It looks like there's a number of interfaces/algorithms that are in the PCLCrypto.Abstractions that are also in PCLCrypto. This leads to issues requiring assembly aliases to properly compile when both are added to a PCL (as per the NuGet).

I'm guessing that the interfaces/enums are intended to be removed from PCLCrypto and just put into the Abstractions?

**Comment by AArnott** [comment]
The Abstractions assembly has already been merged in the 1.0 version on nuget into the other assembly. So I believe this is fixed.

**Comment by onovotny** [comment]
I am using the 1.0.0-beta on NuGet and that's where I got the error. the NuSpec has both assemblies there and there are duplicate types...

**Comment by AArnott** [comment]
Oh dear. I'll look into it.

**Comment by onovotny** [comment]
Looking at the two assemblies (abstractions and pclcrypto) in the portable- nuget dir, they def have duplicates.
