### ISSUE TITLE
key and iv length for AesCbcPkcs7

### ISSUE THREAD

**Issue by tofutim** [AArnott/PCLCrypto#44]
Hi, I was wondering how to know the key and iv length for AesCbcPkcs7. By experiment, I found them to be 32 and 16 by default. Is the 32 fixed? Is the 16 changeable? Is there advantage to changing it?

**Comment by AArnott** [comment]
I think the IV length matches the block size. The block size is something that is configurable in .NET, but not (directly) configurable on WinRT. 
Key length is configurable simply by passing in a key of a different length when you call `CreateSymmetricKey`. I'm not sure whether key length will indirectly determine block size.

As for enumerating legal key sizes, WinRT doesn't expose an API to do this so PCLCrypto doesn't either. In a future version I expect we'll expose such an API in PCLCrypto anyway. For now, you can use the .NET Framework crypto APIs to enumerate key sizes to learn what your options are.
