### ISSUE TITLE
ICryptographicKey.KeySize throws NotImplementedException on Xamarin.Android for symmetric keys

### ISSUE THREAD

**Issue by profhouse** [AArnott/PCLCrypto#5]
Hi,

I have some problem with CreateSymmetricKey - i try use working code copied from WP project, but in XamarinAndroid i have NotImplementedException in KeySize:

![pcl](https://cloud.githubusercontent.com/assets/6103060/5596460/762b1100-928e-11e4-9e1c-dee04a3549ad.png)

I think that it's reason of next exception: Key length not 128/192/256 bits.

Do you have any idea?

**Comment by AArnott** [comment]
@profhouse It seems the Android implementation doesn't implement `KeySize` properly. I'll investigate what if anything we can do in PCLCrypto to implement this.
In the meantime, I believe the problem with your code is exactly as the exception message says: your symmetric key length must match one of the supported lengths.
