### ISSUE TITLE
Encryption/Decryption code breaks on Android 6 Marshmallow (NetFxCrypto.DeriveBytes.GetBytes)

### ISSUE THREAD

**Issue by rsnitsch** [AArnott/PCLCrypto#61]
My encryption/decryption code works perfectly fine up to Android 5.x, but on Android 6 Marshmallow the code doesn't work anymore. The root cause seems to be that the keysize changes from 32 bytes (Android 5) to 16 bytes (Android 6). It seems that the `NetFxCrypto.DeriveBytes.GetBytes` method does not return the correct number of bytes on Android 6.

I am using the following code to derive the keymaterial (the salt has 8 bytes):

    // Returns 32 bytes on Android 5 and 16 bytes on Android 6.
    private byte[] deriveKeyMaterialFromPassword(string password, byte[] salt)
    {
        const int numIterations = 500;
        return NetFxCrypto.DeriveBytes.GetBytes(password, salt, numIterations, 256 / 8);
    }

### Further information

Android 5 device: Google Nexus 4 (Android version 5.1.1)
Android 6 device: Google Nexus 5 (Android version 6.0.1)

### Possibly related links

According to this post on stackoverflow, the default crypto provider was changed in Android 6 from "BC" to "AndroidOpenSSL":
- http://stackoverflow.com/a/34307500

I could not find any official information about this, however. But I have found a related bug report in the Google Android bugtracker:
- Triple DES Encryption generating different Output (https://code.google.com/p/android/issues/detail?id=189292)

**Comment by rsnitsch** [comment]
I forgot to mention that I am using the current PCLCrypto nuget package, version 1.0.86.

**Comment by rsnitsch** [comment]
We are planning to release an app soon, but this issue is a blocker for us. For this reason, I would like to ask you how long you think we will have to wait for you to deal with this issue.

Best regards,
Robert

**Comment by AArnott** [comment]
Thanks for your patience. I've been pretty heads down on getting the first stable release of https://github.com/AArnott/PInvoke released. 

Would you mind trying the latest published beta release to see if that happens to resolve it?

**Comment by rsnitsch** [comment]
Thanks for your quick response.

I tested the DeriveBytes.GetBytes function with the new version and it returns the correct number of bytes. I also retested the function with the old version (because I became suspicious), and it also returns the correct number of bytes. At the moment I can't reproduce the problem at all. I guess I mixed up some variables during my initial debugging session and therefore mistakenly assumed that DeriveBytes.GetBytes returns the wrong number of bytes. Sorry! Just in case, I have extended my code by a check that makes sure the number of bytes is always correct (otherwise, an exception is thrown).

However, I still get this exception during the decryption:

    error:1e06b065:Cipher functions:EVP_DecryptFinal_ex:BAD_DECRYPT

I have verified that the BlockLengths, keyMaterials and KeySizes used/generated on Android 5 and Android 6 are identical. I assume the problem is caused by the new crypto provider in Android 6. See the possibly related links in my first post.

**Comment by AArnott** [comment]
Thanks for the update @rsnitsch. 
It would be incredibly helpful and expedite resolving this if you could add a unit test to this project that includes the encrypt/decrypt code you have that reproduces the problem. That way I can clearly see it, when I've fixed it, and it won't regress. If you send a PR with the test addition, I'll build the fix on top of it and merge.

**Comment by rsnitsch** [comment]
Sorry @AArnott, we have decided to drop PCLCrypto and create our own encryption code for iOS and Android. I will not be able to contribute to a fix for this issue. Sorry.

**Comment by AArnott** [comment]
Well at this point I'm just running existing PCLCrypto tests on the Android 6 emulator two types of tests failed. The trivial to fix NRE, and a `javax.crypto.ShortBufferException` which I've yet to figure out. It's definitely a change in behavior in Android 6, but I'm not sure where the bug is.
