### ISSUE TITLE
PCLCrypto does not support framework .NETPlatform,Version=v5.4

### ISSUE THREAD

**Issue by dguisinger** [AArnott/PCLCrypto#63]
I'm getting the following error message when I try using PCLCrypto in a ASP.NET vNext (5.0 RC1) project when I get PCLCrypto over Nuget.

Error	NU1002	The dependency Validation 2.0.6.15003 in project does not support framework .NETPlatform,Version=v5.4.

**Comment by AArnott** [comment]
Thanks for your report. I'll look into it.

**Comment by dguisinger** [comment]
Thanks.

I created a new project using ASP.NET 5 and the new prerelease beta of AWS
DynamoDB 3.x from NuGet.
PCLCrypto seems to be the only dependency that AWS SDK uses that doesn't
support the new framework.

.NET moved to a new json based project file and dependency system, I
haven't found a way to upgrade a project.
But if you create a new project, it lets you simultaneously target DNX
4.5.1 and DNX Core 5.0 and I'm assuming that's what needs to be done.

Dan

**Comment by AArnott** [comment]
Thanks for the additional background. Yes, I'm familiar with DNX, and PCLCrypto should be able to target it. And I own Validation as well so I'm sure we'll get this sorted out.

**Comment by AArnott** [comment]
Can you explicitly add this dependency to your project.json file?

```
    "Validation": "2.2.5"
```

**Comment by dguisinger** [comment]
That seemed to partially fix it, it originally had two red indicators, one
on PCLCrypto and the other on Validation.
The one on Validation has come off, the one on PCLCrypto didn't change

(see attached)

**Comment by AArnott** [comment]
Thanks. I'll look into PCLCrypto some more. GitHub doesn't do attachments though (from email at least), evidently.

**Comment by dguisinger** [comment]
Happen to figure out what the remaining issue is on PCLCrypto?

**Comment by AArnott** [comment]
Yes. I was able to repro the problem with v1.0.86, which targets .NET 4.0 portable libraries. Such portables don't work on the new platforms.
But v1.1.86-beta targets .NET 4.5 portable profiles, so it *does* support newer platforms including DNX and v5.4. So I'll close this as Fixed. You can use the beta release if you're fine with that in the meantime awaiting a stable release of the newer version.
