### ISSUE TITLE
Compiler error updating to 2.0

### ISSUE THREAD

**Issue by paulanthonymorris** [AArnott/PCLCrypto#79]
I tried to update the nugget package for my Xamarin projects (with PCL libraries). I was getting the following errors on the UWP app so I reverted to 1.0 for now. 
The non-generic type 'PInvoke.NTSTATUS.Code__PInvoke_Windows_Core' cannot be used with type arguments	TestRunner.App.Windows	D:\...SafeTypes.g.cs	415	

The type or namespace name 'Value' could not be found (are you missing a using directive or an assembly reference?)	TestRunner.App.Windows	D:\...\SafeTypes.g.cs	415

**Comment by AArnott** [comment]
Wow. I don't know why any non-generic type would be used with type arguments. That sounds bizarre -- like one of the tools you're using is malfunctioning. Can you provide a repro?

**Comment by paulanthonymorris** [comment]
Yeah it seems like a hed herring. Just creating a UWP project and a PCL and adding the PCL Crypto lib does not result in any errors. So something in my solution is interfering. I will try to get to the bottom of it. FYI: I am getting warnings for the PInvoke.Kernel32 and the PInvoke.NCrypt libs along these lines:
Unresolved P/Invoke method 'NCryptIsKeyHandle!NCrypt' in assembly 'PInvoke.NCrypt, Version=0.1.0.0, Culture=neutral, PublicKeyToken=9e300f9f87f04a7a' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs. TestRunner.App.Windows

**Comment by paulanthonymorris** [comment]
This is the excerpt of IL that is failing (...\TestRunner.App.Windows\obj\x86\Release\ilc\intermediate\JWLibrary.TestRunner.App.Windows.Interop\SafeTypes.g.cs):

namespace PInvoke
{
	[global::System.Runtime.InteropServices.McgRedirectedType("PInvoke.NTSTATUS,PInvoke.Windows.Core, Version=0.1.0.0, Culture=neutral, PublicKeyToken=9e300f9f87f04a7a")]
	public unsafe partial struct NTSTATUS__PInvoke_Windows_Core
	{
		public global::PInvoke.NTSTATUS.Code__PInvoke_Windows_Core <Value>k__BackingField;
	}
}

The error is The type or namespace name 'Value' could not be found (are you missing a using directive or an assembly reference?)

**Comment by AArnott** [comment]
The IL issue you're seeing only shows up when you're compiling for Release, correct? That's the .NET Native compiler and I think this is a bug in that tool chain. Not your fault. I can repro it locally. We should file a bug against dotnet/corefx. I'll file one later today.

**Comment by AArnott** [comment]
Closing, since #81 represents the same issue and focuses on the .NET Native error.
The build warnings have been fixed in PInvoke and will be included in the next release.

**Comment by paulanthonymorris** [comment]
I have updated to the latest on this and everything is working nicely. Thanks for the quick turnaround. .NET native team was helpful also. Really pleased with this package. Great work.
