### ISSUE TITLE
SslStream on PCL

### ISSUE THREAD

**Issue by galvesribeiro** [AArnott/PCLCrypto#8]
Hi Andrew,

I'm trying to get together this PCL socket library to work with SSL/TLS for Secure Sockets: https://github.com/rdavisau/sockets-for-pcl/

I'm using your project for other crypto operations but I wonder if you have if PCLCrypto can help me with that and if yes, can you give me some directions for it?

Thanks!

**Comment by AArnott** [comment]
This library has the crypto, but I imagine secure sockets have a particular protocol of their own for establishing a secret (NTLM, Kerberos, etc.) which this library does not implement. I have no capacity to add that to this library, but I may accept pull requests. :)
