### ISSUE TITLE
Version 2.0 causes .Net native compilation to fail

### ISSUE THREAD

**Issue by AymenDaoudi** [AArnott/PCLCrypto#81]
First, I thank you for the great effort and work you do.

When compiling a uwp app using the .Net native tool chain, there are these errors encountered by the compiler.

> Error Internal compiler error: One or more errors occurred.
> 
> The non-generic type 'PInvoke.NTSTATUS.Code__PInvoke_Windows_Core' cannot be used with type arguments ...obj\x64\Release\ilc\intermediate\Liberte.Windows.Interop\SafeTypes.g.cs 333
> 
> The type or namespace name 'Value' could not be found (are you missing a using directive or an assembly reference?) ...obj\x64\Release\ilc\intermediate\Liberte.Windows.Interop\SafeTypes.g.cs 333

I've posted a thread on [StackOverflow ](http://stackoverflow.com/questions/36144922/error-when-building-uwp-app-in-release-mode) that discusses more this issue .

**Comment by AArnott** [comment]
This is a bug in the .NET Native tool chain. See dotnet/corert#1039 where the issue has been moved to.

**Comment by AArnott** [comment]
I'll send the email that they asked for.

**Comment by AArnott** [comment]
I've sent the email. We'll see what they say.

**Comment by AArnott** [comment]
Ryan Byington said this:

> This is a bug in the .NET Native toolchain. I have opened 205214 to track this issue. 

> You can work around this issue by updating the PInvoke.NTSTATUS type here and the Value property to not use an auto-implemented property and instead define an explicit field(e.g. m_value) for the property.

The workaround sounds entirely doable. I'll file an issue on PInvoke to track.

**Comment by AArnott** [comment]
We'll keep this bug active until PCLCrypto is updated to consume the fix in PInvoke.
