### ISSUE TITLE
Can't use linker in iOS on 2.x

### ISSUE THREAD

**Issue by michaeldimoudis** [AArnott/PCLCrypto#85]
Updated to PCLCrypto 2.x and I can not build my Xamarin iOS app in release mode with linker behaviour "Link Frameworks SDKs Only" because of this error.

`MTOUCH: error MT2002: Failed to resolve "System.Runtime.InteropServices.ComTypes.FILETIME" reference from "System.Runtime.InteropServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"`

It is because of the PInvoke.* PCL libraries.

**Comment by AArnott** [comment]
I'm looking. I don't see the option in Xamarin.iOS to "Link Framework SDKs Only", and none of the settings I do see reproduce the problem you're seeing. I'm upgrading my Xamarin installation now to try to repro with 4.x Xamarin.
In the meantime, if you can tell me which version(s) of PCLCrypto you've tried precisely, that may help.

**Comment by AArnott** [comment]
I suspect this is a bug in Xamarin/mono however, for the record.

**Comment by AArnott** [comment]
With latest Xamarin.iOS installed, I still don't see the option you describe:

![image](https://cloud.githubusercontent.com/assets/3548/14145344/6119519a-f648-11e5-8ae8-020380bd57a1.png)

And the build reports successful.

**Comment by AArnott** [comment]
This is with PCLCrypto 2.0.145 by the way.

**Comment by michaeldimoudis** [comment]
Thanks for looking into it. I think in release mode with link SDK assemblies only and with LLVM compilation is when you can't compile. You are right it probably isn't supported in Xamarin, however someone got it to work by changing the PCL profile as stated here: https://bugzilla.xamarin.com/show_bug.cgi?id=37631

I downgraded to 1.0.86 which allowed me to compile with my release settings (link assemblies & LLVM), however when running app on device I got this error:
`Attempting to JIT compile method 'PCLCrypto.DeriveBytes:GetBytes (string,byte[],int,int)' while running with --aot-only. See http://docs.xamarin.com/ios/about/limitations for more information.`

Searching the net I think this is solved in Cycle 7 of Xamarin which isn't out yet, but it was suggested to downgrade to 1.0.2 in the meantime. This now works for me as expected during compilation and while running on device. I only need a very simple method from PCLCrypto during a log in attempt so I'm fine with 1.0.2.

You can close this issue now, hopefully this information in here will help other people that stumble on this roadblock.

**Comment by AArnott** [comment]
I can't repro the problem even with LLVM enabled. 
Thanks for sharing. I'll close for now. We'll see if anyone else hits this. Hopefully not.

**Comment by ryssel** [comment]
Hi
I'm having the same problem.

I just added PCLCrypto to my iOS project and now I get's:

C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(673,3): error : Failed to resolve "System.Runtime.InteropServices.ComTypes.FILETIME" reference from "System.Runtime.InteropServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"

I have the newest updated Visual Studio Update 2 released yesterday.

**Comment by AArnott** [comment]
Thanks for your report, @ryssel. Can you please add any necessary repro steps that you can think of to help us repro the problem?

**Comment by AlexanderOsokin** [comment]
Same issue on Xamarin.Android  in Release & Xamarin.IOS (Debug & Release) conf ( Using as a part of AWSSDK.Core).

**Comment by raphaaugustosilva** [comment]
Same issue here in 2.0 version or foward.

I'm having this issue in a PCL Xamarin Forms project.

Note: If I build the project with iOS Simulator (iOS 8.2 by the way) it works fine.

The problem is when I build with my real device in the target (iPhone 4S, iOS 9.3.1). It's a "PInvoke" problem

**Comment by AArnott** [comment]
Thanks, @raphaaugustosilva. To be fair, PInvoke isn't doing anything wrong (nor is PCLCrypto). It's only touching APIs that are available in the profile it's targeting. Xamarin is missing these APIs so it's a hole in xamarin.
That said, if we can workaround the problem in PInvoke, I'm certainly open to that possibility. But I need to be able to reproduce it locally to verify a fix. I'll try this again tonight with the new data you and others have submitted here.

**Comment by AArnott** [comment]
Thanks for your report of Android in Release builds, @AlexanderOsokin. I can repro and am looking at possible workarounds we can apply to PInvoke.

**Comment by AArnott** [comment]
Fix included in v2.0.147 that is now on nuget.org

**Comment by michaeldimoudis** [comment]
FYI 2.0.147 allowed me to build and deploy to my iOS device, however when I go to decrypt a string the app crashes. Couldn't get a crash log out, Insights also didn't report the crash. So downgraded back to 1.0.2 again which works good for me, so not a show stopper but thought I'd let you know. If I have time sometime I'll try to dig further to this on device crash scenario.

**Comment by AArnott** [comment]
Thanks for the report, @michaeldimoudis. Yes please open a new issue for this if you can provide a repro.
