### ISSUE TITLE
Linking failed with latest nuget  in Xamarin project

### ISSUE THREAD

**Issue by AlexanderOsokin** [AArnott/PCLCrypto#86]
Reference to metadata item 'System.Runtime.InteropServices.ComTypes.FILETIME' (defined in 'PInvoke.Kernel32, Version=0.2.0.0, Culture=neutral, PublicKeyToken=9e300f9f87f04a7a') from 'PInvoke.Kernel32, Version=0.2.0.0, Culture=neutral, PublicKeyToken=9e300f9f87f04a7a' could not be resolved.

**Comment by AArnott** [comment]
Dupe of #85
