### ISSUE TITLE
ECDiffieHellman export/import private key

### ISSUE THREAD

**Issue by globeport** [AArnott/PCLCrypto#88]
Firstly thankyou for putting together this library. I was wondering, there isn't currently a way to export and import the private key from the ECDiffieHellman class? I tried via reflection using the following but the I end up with two keys, publicKey and privateKey that are identical. Thanks for your help.

```
using (var dh = NetFxCrypto.ECDiffieHellman.Create())
            {
                var platformKey = (SafeKeyHandle)dh.GetPropertyValue("PlatformKey");
                var publicKey = BCryptExportKey(platformKey, null, AsymmetricKeyBlobTypes.BCRYPT_ECCPUBLIC_BLOB).ToArray();
                var privateKey = BCryptExportKey(platformKey, null, AsymmetricKeyBlobTypes.BCRYPT_ECCPRIVATE_BLOB).ToArray();
}
```

**Comment by AArnott** [comment]
BCrypt doesn't support exporting the private key from what I've been able to tell. NCrypt is the library that lets you export private keys but it doesn't seem to support ECC if I recall correctly. But I'd be happy to be proven wrong.

**Comment by globeport** [comment]
OK thanks, rolling back to bouncy castle for now, cant seem to find an obvious solution to this at the moment.
