### ISSUE TITLE
AesCbcPkcs7 key sizes inconsistent between UWP and .NET 

### ISSUE THREAD

**Issue by GeertvanHorrik** [AArnott/PCLCrypto#89]
Running on UWP (works):

```
var provider = SymmetricKeyAlgorithmProvider.OpenAlgorithm(SymmetricAlgorithm.AesCbcPkcs7);
var randomBytes = CryptographicBuffer.GenerateRandom(256);
var randomKey = provider.CreateSymmetricKey(randomBytes);
```

Running on Desktop (.net 4.6.1) (does not work):

```
var provider = SymmetricKeyAlgorithmProvider.OpenAlgorithm(SymmetricAlgorithm.AesCbcPkcs7);
var randomBytes = CryptographicBuffer.GenerateRandom(256);
var randomKey = provider.CreateSymmetricKey(randomBytes);
```

"The specified key is not a valid size for this algorithm."

Even when I use exactly the same byte array for the key on both platforms, desktop cannot create the key.

**Comment by AArnott** [comment]
The symmetric key size you're using is excessively large. 256 bytes = 2048 bits. For AES, [256 bits is usually the max](https://en.wikipedia.org/wiki/Advanced_Encryption_Standard).
I think then you mistakenly specified 256 to `GenerateRandom` when you meant `256 / 8 = 32`.

The fact that WinRT accepted it is surprising. But .NET is not incorrect to reject it. PCLCrypto doesn't guarantee that every platform accept all the same key sizes. On the contrary, each platform's crypto support is used so PCLCrypto cannot exceed what the platform offers. You can enumerate valid key sizes using the `ISymmetricKeyAlgorithmProvider.LegalKeySizes` property.

But as I say, this should work just fine, once you fix your key size.

**Comment by GeertvanHorrik** [comment]
Wow, that's double stupid:

1. My mixing up bits and bytes (sorry for th aT)
2. The UWP platform not throwing an exception on that extremely large key

Anyway, it's fixed, thanks.
