### ISSUE TITLE
Failed to resolve PCLCrypto.ISymmetricKeyAlgorithmProvider

### ISSUE THREAD

**Issue by adamfisher** [AArnott/PCLCrypto#91]
Updated to the latest **2.0.147** and keep getting an error when building a Xamarin iOS project. It makes use of the XamariniOS10 nuget target. Worked fine before this.

```
Error	17	Failed to resolve "PCLCrypto.ISymmetricKeyAlgorithmProvider 
PCLCrypto.ISymmetricKeyAlgorithmProviderFactory::OpenAlgorithm(PCLCrypto.SymmetricAlgorithm)"
reference from "PCLCrypto, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d4421c8a4786956c"
MyMobileApp.iOS
```

**Comment by AArnott** [comment]
Your error mentions PCLCrypto version 1.0 (in the error message itself). It looks like you may have an errant reference to an old PCLCrypto somewhere. I'm guessing you are referencing an assembly that itself was compiled against an older version of PCLCrypto. Can you check?

**Comment by adamfisher** [comment]
That did the trick. Forgot I referenced it from a parent library. Sorry for the trouble.
