### ISSUE TITLE
Length does not a multiple of block size and no padding is selected. Parameter name: data

### ISSUE THREAD

**Issue by mamathakalaiah** [AArnott/PCLCrypto#92]
I have mobile application written using Xamarin.Forms for Android and iOS.
I am using PCLCrypto from initial of my app. The app is in app stores and have been undergone multiple updates.
I use encryption and decryption for storing user data in the app.

My issue is for this release:
I get the below exception during decrypt:
_Length does not a multiple of block size and no padding is selected. Parameter name: data_

This was working in my previous app releases, but now we need to update the app on the store and this is not working.
Kindly let me know were we are going wrong.

Here is my code snippet.

`			

		public byte[] iv;
		public ICryptographicKey key;
                
                void CryptoInit()
		{
			byte[] salt = new byte[saltString.Length * sizeof(char)];
			Buffer.BlockCopy(saltString.ToCharArray(), 0, salt, 0, salt.Length);

			byte[] keyMaterial = NetFxCrypto.DeriveBytes.GetBytes(keyString, salt, iteration, 32);

			var provider = WinRTCrypto.SymmetricKeyAlgorithmProvider.OpenAlgorithm(SymmetricAlgorithm.AesCbcPkcs7);
			key = provider.CreateSymmetricKey(keyMaterial);
			iv = null; // this is optional, but must be the same for both encrypting and decrypting
		}

		byte[] Encrypt(string plainText)
		{
			byte[] data = new byte[plainText.Length * sizeof(char)];
			Buffer.BlockCopy(plainText.ToCharArray(), 0, data, 0, data.Length);

			byte[] cipherText = WinRTCrypto.CryptographicEngine.Encrypt(key, data, iv);
			return cipherText;
		}

		string Decrypt(byte[] cipherText)
		{
			try {
				byte[] plainText = WinRTCrypto.CryptographicEngine.Decrypt(key, cipherText, iv);

				char[] chars = new char[plainText.Length / sizeof(char)];
				Buffer.BlockCopy(plainText, 0, chars, 0, plainText.Length);
				return new string(chars);
			} catch (Exception ex) {
				LogError (ex);
				return null;
			}
		}`

**Comment by AArnott** [comment]
Your exception message "Length does not a multiple..." appears in older versions of PCLCrypto. Have you tried using the latest version?

From your code, I see you're selecting `AesCbcPkcs7` which does include padding. So the error you're seeing seems inappropriate, if this is truly the code that your app has.

**Comment by mamathakalaiah** [comment]
I have updated the PCLCrypto.

The code is the exact one I have in my app.

**Comment by mamathakalaiah** [comment]
The issue exist in Release mode of the applications

**Comment by mamathakalaiah** [comment]
The stack trace during debug is as follows:

Length is not a multiple of block size and no padding is selected.
Length is not a multiple of block size and no padding is selected.
Parameter name: data
Parameter name: data
  at Validation.Requires.Argument (Boolean condition, System.String parameterName, System.String message) [0x00003] in <filename unknown>:0 
  at Validation.Requires.Argument (Boolean condition, System.String parameterName, System.String message) [0x00003] in <filename unknown>:0 
  at PCLCrypto.SymmetricCryptographicKey.Decrypt (System.Byte[] data, System.Byte[] iv) [0x0004f] in <filename unknown>:0 
  at PCLCrypto.CryptographicEngine.Decrypt (ICryptographicKey key, System.Byte[] data, System.Byte[] iv) [0x00018] in <filename unknown>:0

**Comment by AArnott** [comment]
This error occurs when the ciphertext you pass to the Decrypt method isn't exactly the size that came from the Encrypt method. Can you double-check the array length at each of those points?

**Comment by AArnott** [comment]
Closing due to lack of requested data.
