### ISSUE TITLE
(Documentation) Typo in RFC number provided for CryptographicPublicKeyBlobType.Pkcs1RsaPublicKey

### ISSUE THREAD

**Issue by magikm18** [AArnott/PCLCrypto#94]
The current documentation reads:

> The key is an RSA public key defined in the PKCS #1 standard. For more information, see the RSA Cryptography Specification in RFC 3347.

However, RFC 3347 is completely unrelated to RSA or PKCS; the correct document is RFC 3447. Likely a minor typo, however it will cause confusion for anyone is trying to find documentation on the format.

**Comment by AArnott** [comment]
Thanks for the report, @magikm18. Does the linking commit clear it up then?

**Comment by magikm18** [comment]
Yes, it appears to be correct now.
