### ISSUE TITLE
Assymetric encryption on Android

### ISSUE THREAD

**Issue by ddobrev** [AArnott/PCLCrypto#96]
WinRTCrypto.CryptographicEngine.CreateEncryptor throws a NotSupportedException on Android. This feature is particularly important because the Android Keystore can only hold asymmetric keys before Android 6.

**Comment by AArnott** [comment]
Asymmetric encryption should certainly work on Android. Can you please include the exception type, message, and entire callstack?

Sometimes folks get confused and say it threw a NotSupportedException when it actually threw a NotImplementedException, and that would happen if you were referencing the reference assembly instead of the platform assembly (usually because you didn't install the nuget reference into the android app project itself).

**Comment by ddobrev** [comment]
It's the exception at https://github.com/AArnott/PCLCrypto/blob/4a511f69f48d8c0613e5a4736bd710848551fe75/src/PCLCrypto.Shared.PlatformCommon/CryptographicKey.cs#L123 . It makes sense because CryptographicKey.CreateEncryptor is never overridden in https://github.com/AArnott/PCLCrypto/tree/master/src/PCLCrypto.Android .

**Comment by AArnott** [comment]
[Yes it is overridden](https://github.com/AArnott/PCLCrypto/blob/master/src/PCLCrypto.Android/SymmetricCryptographicKey.cs#L126)

But you may be looking at the RSACryptographicKey class, where it is not. No platform overrides it. CreateEncryptor is for streaming encryption. And RSA encryption is for encrypting symmetric keys -- not streams of data. To encrypt your symmetric key (which does support streaming) with an RSA public key, use CryptographicEngine.Encrypt.

**Comment by ddobrev** [comment]
You may have missed that I edited my comment, it used to say "is not overridden" but I changed it to "is only overridden for symmetric keys".
Anyway, my symmetric key has to be saved too, therefore I need to encrypt its file using RSA. So in the end I am still going to need an asymmetric encryption provider to pass to CryptoStream.

**Comment by AArnott** [comment]
RSA encryption is *extremely* limited in the length of the buffer it can encrypt -- just barely enough for a symmetric key. So encrypt it while it's still in memory (right after or before you use it) using CryptographicEngine.Encrypt as I directed. 
There is no streaming support such that you could encrypt a file with RSA.
