### ISSUE TITLE
Build failed on build hosts

### ISSUE THREAD

**Issue by martb1n** [AArnott/PCLCrypto#98]
Hello. I have some problems. 
I use PCLCrypto in Xamarin project. When I try to build project on local machine under Visual Studio - all good. But when I try to use online build systems (VSTS, bitrise.io), I got errors

this log from bitrise.io
```
Library/Frameworks/Mono.framework/Versions/4.2.3/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'PCLCrypto, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d4421c8a4786956c, processorArchitecture=MSIL' not resolved
/Library/Frameworks/Mono.framework/Versions/4.2.3/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'Validation, Version=2.2.0.0, Culture=neutral, PublicKeyToken=2fc06f0d701809a7, processorArchitecture=MSIL' not resolved   
```

and this one from VSTS
`C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): Warning MSB3245: Could not resolve this reference. Could not locate the assembly "PCLCrypto, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d4421c8a4786956c, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.`

Can you help me? What I missed?

**Comment by AArnott** [comment]
Did you use NuGet to install PCLCrypto into your project? Did your build definition perform a package restore before building?
Does your solution involve multiple uses of PCLCrypto and perhaps some are using an older version (1.x) than others that use (2.x)? You should make sure they're all using the same version.

**Comment by martb1n** [comment]
Yes, I use Nuget. yes, build definition perform package resotore.

No, I checked. All projects are using v.2.0.140

**Comment by AArnott** [comment]
I suspect there's something else weird going on here. Generally I expect (and observe) that cloud builds work just fine with this package, including VSTS and AppVeyor.
I suggest you study more of the log than you've pasted here. Look for where the files are restored, where they are copied to (and not copied). Perhaps you can use VSTS's "copy and publish artifacts" with "always run" checked to salvage your entire source tree folder after the failure so you can download that and try locally what failed in the cloud to get more insight into it.

I'm afraid I won't have more time to spend investigating it with you though. Good luck.

**Comment by Beej126** [comment]
i brought this error on myself - [see here](https://github.com/xamarin/Xamarin.Auth/issues/123#issuecomment-256238670)
