### ISSUE TITLE
Support for OSX

### ISSUE THREAD

**Issue by robbpriestley** [AArnott/PCLCrypto#99]
Hi, I've got an ASP.NET Core project I'm building on OSX and I want to utilize an aspect of the Amazon Web Services SDK. Turns out PCLCrypto is a requirement for the AWS SDK, so I added `"PCLCrypto": "2.0.147"` as a `dependency` to my `project.json`

At runtime, I get the following exception message:

> PCLCrypto.NotImplementedByReferenceAssemblyException: This is a reference assembly and does not contain implementation. Be sure to install the PCLCrypto package into your application so the platform implementation assembly will be used at runtime.

I'm just not sure what that means or how to deal with it. Haven't I already "installed" it by adding the dependency? When I do a `dotnet restore` on my project, I believe NuGet does "install" the package, does it not? Do I need some sort of actual DLL imported into my project structure?

**Comment by AArnott** [comment]
I realized this would be a problem only a couple weeks ago. Thanks for filing the issue. I believe it will work if you target net46. It's 'dnxcore' that isn't supported by PCLCrypto at this point. Can you confirm whether targeting net46 in your ASP.NET Core project fixes the problem?

**Comment by robbpriestley** [comment]
Unfortunately, seemingly not. I tried a few experiments and the only way I seem to be able to "target" (sorry, you may need to define that in more detail if I've got it wrong) net46 is as follows. This restores and compiles ok, but results in no change at runtime. If I add net46 higher up in the imports clause, I get a pretty massive, (but obviously unrelated) compatibility blowup at runtime. I'll work on other areas in my project for the time being if you want to suggest any other things for me to try.
```
"frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net46+win8"
      ]
    }
```
  },

**Comment by AArnott** [comment]
I don't mean adding it to that imports list, no. I mean add it to your frameworks list:

```json
"frameworks": {
    "netcoreapp1.0": { /* ... */ },
    "net46": { }
  },
```

**Comment by robbpriestley** [comment]
Oh, I see. OK, I have tried it. Awfully sorry but when I do that, my whole project goes completely haywire. I'm just not enough of an expert in the intricacies of project.json to be able to figure it out, especially considering how much the format has continued to change. Sorry.
![screenshot](https://cloud.githubusercontent.com/assets/16694050/15437615/05d67a62-1e7d-11e6-85ca-333fe8df5d14.jpg)

**Comment by AArnott** [comment]
OK. Thanks for trying. I'll of course leave this issue open. I do want to get it fixed, and can experiment and figure it out.
It may be a few weeks before I get started though.

**Comment by robbpriestley** [comment]
Sure, no problem. Unfortunately at this point I am probably going to need to find an alternative to AWS SDK, and by extension, PCLCrypto to achieve my development goals. But of course these are the risks being an early adopter so I completely understand. Thanks for your help!

**Comment by AArnott** [comment]
Actually I totally missed one key word in your opening statement: OSX. 
PCLCrypto doesn't support OSX. It supports iOS, Android, and various Windows platforms. But not OSX.  I imagine adding such support would probably be relatively trivial given iOS and OSX are supposedly quite similar. 

I just tried ASP.NET Core on Windows with PCLCrypto and it worked just fine. So I'll consider this issue a request for OSX support.

**Comment by robbpriestley** [comment]
I think now that .NET Core is cross-platform theoretically you'll need to consider Linux support as well? But, I can't say for sure and that'll need to be your choice how to proceed as I have already found an alternative an moved past this. 

I assume the reason why I encountered this in the first plave is because the AWS .NET SDK was written to target Windows and hasn't been fully upgraded for .NET Core or the notion that someone like me might try to use it on a Mac. It's a bit of an adventure. Anyway, thanks again.

**Comment by AArnott** [comment]
CoreCLR support isn't particularly a goal of PCLCrypto, since CoreCLR already has a standardized crypto API. PCLCrypto is about bringing a consistent API everywhere else--it existed before CoreCLR did with any promise of a unified API. So where folks are building on CoreCLR to begin with, I might expect them to use CoreCLR APIs.
As CoreCLR will not likely offer a crypto API that bridges multiple platforms beyond CoreCLR, PCLCrypto *may* offer that bridge, bringing it to CoreCLR as well, perhaps including Linux. 
Something to consider though.

**Comment by AArnott** [comment]
We will reconsider OSX support when and if targeting it becomes possible from Windows. 
Linux support is interesting, when Core CLR SDK stabilizes more.
